// ===== 球员中文名映射 (Wikidata + 本地) =====
// 生成: 2026-06-23T12:10:20.191Z | 覆盖: 622/26357 (2.4%)
window.__playerCNMap = {
 "Théo Hernandez": "特奥·埃尔南德斯",
 "Mitsuki Hidaka": "日髙 光揮",
 "Taisei Kuwata": "桒田 大誠",
 "Rinto Hanashiro": "花城 琳斗",
 "Shuto Nagano": "永野 修都",
 "Gotoku Sakai": "酒井 高徳",
 "Takahiro Nakazato": "中里 崇宏",
 "Shogo Nishikawa": "西河 翔吾",
 "Kentaro Sato": "佐藤 健太郎",
 "Takumi Yamada": "山田 拓巳",
 "Manabu Saito": "齋藤 学",
 "Hinata Gonda": "権田 陽大",
 "Takashi Usami": "宇佐美 貴史",
 "Shunya Suganuma": "菅沼 駿哉",
 "Kaito Matsuzawa": "松澤 海斗",
 "Kazuyoshi Miura": "三浦 知良",
 "Kento Hamasaki": "濱﨑 健斗",
 "Yumeki Yoshinaga": "吉永 夢希",
 "Soma Anzai": "安斎 颯馬",
 "Keigo Higashi": "東 慶悟",
 "Masaaki Higashiguchi": "東口 順昭",
 "Hiroki Sekine": "関根 大輝",
 "Shunsuke Ando": "安藤 駿介",
 "Masato Kudo": "工藤 壮人",
 "Kyohei Noborizato": "登里 享平",
 "Shohei Takahashi": "高橋 祥平",
 "Rento Takaoka": "高岡 伶颯",
 "Kosuke Taketomi": "武富 孝介",
 "Yuya Osako": "大迫 勇也",
 "Takuya Wada": "和田 拓也",
 "Ryo Nagai": "永井 龍",
 "Kohei Kawata": "河田 晃兵",
 "Tsuyoshi Kodama": "児玉 剛",
 "Harry Kane": "哈里·凯恩",
 "Raheem Sterling": "拉希姆·斯特林",
 "Suguru Hino": "日野 優",
 "Kunimitsu Sekiguchi": "関口 訓充",
 "Nobuteru Nakagawa": "中川 敦瑛",
 "Álvaro Morata": "阿尔瓦罗·莫拉塔",
 "Toshio Shimakawa": "島川 俊郎",
 "Ryo Miyaichi": "宮市 亮",
 "Gaku Shibasaki": "柴崎 岳",
 "Yoshiaki Takagi": "高木 善朗",
 "Kenyu Sugimoto": "杉本 健勇",
 "Tatsuya Uchida": "内田 達也",
 "Yuki Horigome": "堀米 勇輝",
 "Sung-jun Yoon": "윤성준 尹 星俊",
 "Hosei Kijima": "木島 萌生",
 "Goro Kawanami": "川浪 吾郎",
 "Nico Yennaris": "Nicholas Harry Yennaris ; 李可",
 "Daley Blind": "戴利·布林德",
 "Yutaro Tsukada": "塚田 悠太郎",
 "Antoine Griezmann": "安托万·格里兹曼",
 "Koki Kumasaka": "熊坂 光希",
 "Tatsuya Morita": "守田 達弥",
 "Hideomi Yamamoto": "山本 英臣",
 "Hisashi Jogo": "城後 寿",
 "Mizuki Hamada": "濱田 水輝",
 "Kenta Tanno": "丹野 研太",
 "Hotaru Yamaguchi": "山口 蛍",
 "Yu Kobayashi": "小林 悠",
 "Virgil van Dijk": "维吉尔·范迪克",
 "Enner Valencia": "恩纳·瓦伦西亚",
 "Takahiro Ogihara": "扇原 貴宏",
 "Yoshifumi Kashiwa": "柏 好文",
 "Kohei Kiyama": "喜山 康平",
 "Yuki Kobayashi": "小林 友希",
 "Wataru Endo": "遠藤 航",
 "Manuel Bleda": "洛迪古斯 Manuel Bleda Rodríguez",
 "Ryan Hirooka": "広岡 ライアン勇輝 , Ryan Yuki Hirooka",
 "Ryota Nagaki": "永木 亮太",
 "Tyias Browning": "Tyias Charles Browning, 蒋光太",
 "Tomohiko Murayama": "村山 智彦",
 "Yuki Muto": "武藤 雄樹",
 "Shoma Doi": "土居 聖真",
 "Ryota Oshima": "大島 僚太",
 "Gen Shoji": "昌子 源",
 "Adrien Rabiot": "阿德里安·拉比奥",
 "Kento Hashimoto": "橋本 拳人",
 "Ming-Yang Yang": "杨明洋",
 "Yuya Kubo": "久保 裕也",
 "Yuzo Iwakami": "岩上 祐三",
 "Tatsuki Nara": "奈良 竜樹",
 "Shoya Nakajima": "中島 翔哉",
 "Sei Muroya": "室屋 成",
 "Ayumi Niekawa": "牲川 歩見",
 "Naomichi Ueda": "植田 直通",
 "Yuto Shirai": "白井 裕人",
 "Karim Benzema": "卡里姆·本泽马",
 "Shinya Yajima": "矢島 慎也",
 "Andreas Christensen": "安德烈亚斯·克里斯滕森",
 "Tatsuya Tanaka": "田中 達也",
 "Takayuki Mae": "前 貴之",
 "Fumiya Hayakawa": "早川 史哉",
 "Yuto Horigome": "堀米 悠斗",
 "Takuya Iwanami": "岩波 拓也",
 "Kyohei Yoshino": "吉野 恭平",
 "Takumi Minamino": "南野 拓実",
 "Memphis Depay": "孟菲斯·德佩",
 "Kasper Schmeichel": "卡斯帕·舒梅切尔",
 "Noriyoshi Sakai": "酒井 宣福",
 "Ryosuke Yamanaka": "山中 亮輔",
 "Manuel Neuer": "曼努埃尔·诺伊尔",
 "Sai van Wermeskerken": "ファン ウェルメスケルケン 際",
 "Hayato Nakama": "仲間 隼斗",
 "Kazuki Saito": "齊藤 和樹",
 "Nathan Aké": "纳坦·阿克",
 "Tsukasa Shiotani": "塩谷 司",
 "Hiroki Fujiharu": "藤春 廣輝",
 "Hugo Lloris": "雨果·洛里斯",
 "Shota Kawanishi": "川西 翔太",
 "Piotr Zieliński": "彼得·泽林斯基",
 "Ken Iwao": "岩尾 憲",
 "Shota Arai": "新井 章太",
 "Kosuke Kinoshita": "木下 康介",
 "Yuki Nogami": "野上 結貴",
 "Junki Kanayama": "金山 隼樹",
 "Il-gyu Park": "朴 一圭 , パク イルギュ",
 "Yoshinori Muto": "武藤 嘉紀",
 "Akira Ibayashi": "井林 章",
 "David Kong": "卡杜素 , David Rui de Kong Cardoso",
 "Rivaldo": "里瓦尔多",
 "Jack Grealish": "杰克·格里利什",
 "Tomoya Inukai": "犬飼 智也",
 "Daiki Watari": "渡 大生",
 "Haruya Ide": "井出 遥也",
 "Romário": "罗马里奥",
 "Riki Harakawa": "原川 力",
 "Yuji Takahashi": "高橋 祐治",
 "Keita Hidaka": "日高 慶太",
 "Sho Sasaki": "佐々木 翔",
 "Ryohei Shirasaki": "白崎 凌兵",
 "Paulo Junichi Tanaka": "田中 パウロ 淳一",
 "Shun Takagi": "高木 駿",
 "Kohei Mihara": "三原 向平",
 "Keigo Numata": "沼田 圭悟",
 "Gakuji Ota": "太田 岳志",
 "Takeshi Kanamori": "金森 健志",
 "Yosuke Yuzawa": "湯澤 洋介",
 "Pedro Delgado": "Pedro Miguel Gomes Delgado, 德尔加多",
 "Pêpê": "佩佩",
 "Kazuhiro Sato": "佐藤 和弘",
 "Marcus Rashford": "马库斯·拉什福德",
 "Kosuke Shirai": "白井 康介",
 "Yuzuru Shimada": "島田 譲",
 "Hayao Kawabe": "川辺 駿",
 "Yusuke Chajima": "茶島 雄介",
 "Bruno Fernandes": "布鲁诺·费尔南德斯",
 "Yoshihiro Nakano": "中野 嘉大",
 "Kingsley Coman": "金斯利·科曼",
 "Takuma Asano": "浅野 拓磨",
 "Naoki Maeda": "前田 直輝",
 "Daiki Kogure": "小暮 大器",
 "Yuhei Sato": "佐藤 優平",
 "Tomoki Imai": "今井 智基",
 "Sergio Ramos": "塞尔希奥·拉莫斯",
 "Yuki Honda": "本多 勇喜",
 "Kylian Mbappé": "基利安·姆巴佩",
 "Yoshinori Suzuki": "鈴木 義宜",
 "Dayot Upamecano": "达约·于帕梅卡诺",
 "Teruhito Nakagawa": "仲川 輝人",
 "Yuma Suzuki": "鈴木 優磨",
 "Hisashi Ohashi": "大橋 尚志",
 "Yuta Nakayama": "中山 雄太",
 "Hiroki Noda": "野田 裕喜",
 "Shintaro Kurumaya": "車屋 紳太郎",
 "Junya Ito": "伊東 純也",
 "Taiga Maekawa": "前川 大河",
 "Alexander Isak": "伊萨克",
 "Yoichi Naganuma": "長沼 洋一",
 "Kazune Kubota": "久保田 和音",
 "Tsukasa Morishima": "森島 司",
 "Koki Ogawa": "小川 航基",
 "Marco Reus": "罗伊斯",
 "Yuki Nakashima": "中島 裕希",
 "Luka Modrić": "卢卡·莫德里奇",
 "Lionel Messi": "利昂内尔·梅西",
 "Steven Bergwijn": "史蒂文·贝尔温",
 "Ryosuke Kojima": "小島 亨介",
 "Yuta Koike": "小池 裕太",
 "Ousmane Dembélé": "奥斯曼·登贝莱",
 "Sho Inagaki": "稲垣 祥",
 "Hirving Lozano": "伊尔文·洛萨诺",
 "Yosuke Ideguchi": "井手口 陽介",
 "Denzel Dumfries": "登泽尔·邓弗里斯",
 "Matthijs de Ligt": "马泰斯·德利赫特",
 "Frenkie de Jong": "弗雷基·德容",
 "Akito Fukuta": "福田 晃斗",
 "Dani Olmo": "达尼·奥尔莫",
 "Kento Misao": "三竿 健斗",
 "Rikiya Motegi": "茂木 力也",
 "Koji Miyoshi": "三好 康児",
 "Ryoma Watanabe": "渡邊 凌磨",
 "Guillermo Ochoa": "吉列尔莫·奥乔亚",
 "Koya Yuruki": "汰木 康也",
 "Takahiro Sekine": "関根 貴大",
 "Masaya Okugawa": "奥川 雅也",
 "Mehdi Taremi": "迈赫迪·塔雷米",
 "Ko Matsubara": "松原 后",
 "Shogo Taniguchi": "谷口 彰悟",
 "Kentaro Kakoi": "圍 謙太朗",
 "Ado Onaiwu": "オナイウ 阿道",
 "Jun Amano": "天野 純",
 "Tomoya Koyamatsu": "小屋松 知哉",
 "Hiroyuki Mae": "前 寛之",
 "Yohei Takaoka": "高丘 陽平",
 "Naoki Nomura": "野村 直輝",
 "Rikuto Hirose": "広瀬 陸斗",
 "Taiki Tamukai": "田向 泰輝",
 "Eiji Shirai": "白井 永地",
 "Eiichi Katayama": "片山 瑛一",
 "Kazuaki Mawatari": "馬渡 和彰",
 "Kazuhiko Chiba": "千葉 和彦",
 "Koki Anzai": "安西 幸輝",
 "Kei Koizumi": "小泉 慶",
 "Christian Pulisic": "克里斯蒂安·普利西奇",
 "Takaaki Shichi": "志知 孝明",
 "Tatsuya Ito": "伊藤 達哉",
 "Robert Lewandowski": "罗伯特·莱万多夫斯基",
 "Yasuki Kimoto": "木本 恭生",
 "Cayman Togashi": "富樫 敬真 Cayman Graybill Togashi",
 "Tatsuya Hasegawa": "長谷川 竜也",
 "Daiki Hashioka": "橋岡 大樹",
 "Go Hatano": "波多野 豪",
 "Shintaro Nago": "名古 新太郎",
 "Yuta Imazu": "今津 佑太",
 "Yuya Yamagishi": "山岸 祐也",
 "Takuma Nishimura": "西村 拓真",
 "Ryoya Ogawa": "小川 諒也",
 "Mitsuki Saito": "齊藤 未月",
 "Keigo Tsunemoto": "常本 佳吾",
 "Hiroki Ito": "伊藤 洋輝",
 "Toshiki Takahashi": "高橋 利樹",
 "Yuto Iwasaki": "岩崎 悠人",
 "Kengo Kitazume": "北爪 健吾",
 "Ko Itakura": "板倉 滉",
 "Ataru Esaka": "江坂 任",
 "Daichi Kamada": "鎌田 大地",
 "Hayato Nukui": "温井 駿斗",
 "Jurato Ikeda": "池田 樹雷人",
 "Masataka Nishimoto": "西本 雅崇",
 "Tomoki Iwata": "岩田 智輝",
 "Rafael Leão": "拉斐尔·莱昂",
 "Declan Rice": "德克兰·赖斯",
 "Ritsu Doan": "堂安 律",
 "Kohei Tezuka": "手塚 康平",
 "Masaaki Murakami": "村上 昌謙",
 "Yuji Hoshi": "星 雄次",
 "Vinicius Junior": "维尼修斯",
 "Akira Fantini": "ファンティーニ 燦",
 "Ryuji Izumi": "和泉 竜司",
 "Achraf Hakimi": "哈基米",
 "Ferran Torres": "费兰·托雷斯",
 "Tetsushi Yamakawa": "山川 哲史",
 "Ayumu Seko": "瀬古 歩夢",
 "Yukinari Sugawara": "菅原 由勢",
 "Shimpei Fukuoka": "福岡 慎平",
 "Taisei Miyashiro": "宮代 大聖",
 "Keito Nakamura": "中村 敬斗",
 "Issei Ouchi": "大内 一生",
 "Soichiro Kozuki": "上月 壮一郎",
 "Takefusa Kubo": "久保 建英",
 "Phil Foden": "菲尔·福登",
 "Reiya Morishita": "森下 怜哉",
 "Ismaïla Sarr": "伊斯梅拉·萨尔",
 "Atsushi Kawata": "河田 篤秀",
 "Aurélien Tchouaméni": "奥雷利安·楚阿梅尼",
 "Ryo Hatsuse": "初瀬 亮",
 "Taiki Hirato": "平戸 太貴",
 "Yuki Kakita": "垣田 裕暉",
 "Koki Machida": "町田 浩樹",
 "Satoki Uejo": "上門 知樹",
 "Ryotaro Ito": "伊藤 涼太郎",
 "Kanya Fujimoto": "藤本 寛也",
 "Keisuke Osako": "大迫 敬介",
 "Tomoya Wakahara": "若原 智哉",
 "Keiya Shiihashi": "椎橋 慧也",
 "Masato Tokida": "常田 克人",
 "Kaito Anzai": "安西 海斗",
 "Kazunari Ichimi": "一美 和成",
 "Masato Yuzawa": "湯澤 聖人",
 "Erling Haaland": "埃尔林·哈兰德",
 "Masayuki Okuyama": "奥山 政幸",
 "Masaya Tashiro": "田代 雅也",
 "Daizen Maeda": "前田 大然",
 "Jun Okano": "岡野 洵",
 "Kosuke Saito": "齋藤 功佑",
 "Shugo Tsuji": "辻 周吾",
 "Hiromu Mitsumaru": "三丸 拡",
 "Keita Endo": "遠藤 渓太",
 "Shun Nakamura": "中村 駿",
 "Daichi Tagami": "田上 大地",
 "Daigo Araki": "荒木 大吾",
 "Alphonso Davies": "阿方索·戴维斯",
 "Ivan Perišić": "伊万·佩里西奇",
 "Luis Suárez": "路易斯·苏亚雷斯",
 "Ren Komatsu": "小松 蓮",
 "Zion Suzuki": "鈴木 彩艶",
 "Ryotaro Ishida": "石田 凌太郎",
 "Taichi Yamasaki": "山﨑 大地",
 "Rihito Yamamoto": "山本 理仁",
 "Yutaro Oda": "小田 裕太郎",
 "Fuki Yamada": "山田 楓喜",
 "Bukayo Saka": "布卡约·萨卡",
 "Cody Gakpo": "科迪·加克波",
 "Yuya Nakasaka": "中坂 勇哉",
 "Kyosuke Tagawa": "田川 亨介",
 "Teruki Hara": "原 輝綺",
 "Wojciech Szczesny": "沃伊切赫·什琴斯尼",
 "Edouard Mendy": "爱德华·门迪",
 "Shinji Yamada": "山田 真史",
 "Omar Marmoush": "马尔穆什",
 "Masaaki Takahara": "高原 正旭",
 "Yosuke Hanya": "半谷 陽介",
 "Shinta Appelkamp": "Shinta Karl Appelkamp , アペルカンプ 真大 カール",
 "Shun Shibata": "柴田 駿",
 "Ángel Di María": "安赫尔·迪马利亚",
 "Takahiro Ko": "高 宇洋",
 "Ayumu Kawai": "川井 歩",
 "Takahiro Iida": "飯田 貴敬",
 "Kota Yamada": "山田 康太",
 "Yugo Tatsuta": "立田 悠悟",
 "Kaito Abe": "阿部 海大",
 "Haruki Saruta": "猿田 遥己",
 "Hiroki Abe": "安部 裕葵",
 "Leo Takae": "高江 麗央",
 "Taishi Matsumoto": "松本 泰志",
 "Daiya Maekawa": "前川 黛也",
 "Takuya Yasui": "安井 拓也",
 "Taiyo Koga": "古賀 太陽",
 "Ao Tanaka": "田中 碧",
 "Kaina Yoshio": "吉尾 海夏",
 "Wakaba Shimoguchi": "下口 稚葉",
 "Shohei Takeda": "武田 将平",
 "Takuya Shimamura": "島村 拓弥",
 "Keiya Sento": "仙頭 啓矢",
 "Koki Tsukagawa": "塚川 孝輝",
 "Akinori Ichikawa": "市川 暉記",
 "Hiroki Mawatari": "馬渡 洋樹",
 "Ryo Toyama": "外山 凌",
 "Yuki Omoto": "大本 祐槻",
 "Kyogo Furuhashi": "古橋 亨梧",
 "Atsuki Ito": "伊藤 敦樹",
 "Takuya Ogiwara": "荻原 拓也",
 "Koki Yonekura": "米倉 恒貴",
 "Taichi Hara": "原 大智",
 "Reo Hatate": "旗手 怜央",
 "Oliver Gerbig": "周緣德 Oliver Benjamin Gerbig",
 "Yota Shimokawa": "下川 陽太",
 "Shosei Okamoto": "岡本 將成",
 "Leo Kokubo": "小久保 玲央 ブライアン - Leo Brian Kokubo",
 "Shota Fujio": "藤尾 翔太",
 "Koki Saito": "斉藤 光毅",
 "Seiji Kimura": "木村 誠二",
 "Taiki Yamada": "山田 大樹",
 "Yuya Takazawa": "髙澤 優也",
 "Jelani Reshaun Sumiyoshi": "住吉 ジェラニレショーン",
 "Tomoki Takamine": "高嶺 朋樹",
 "Kaoru Mitoma": "三笘 薫",
 "Kaito Taniguchi": "谷口 海斗",
 "Shogo Asada": "麻田 将吾",
 "Koki Fukui": "福井 光輝",
 "Takuya Shigehiro": "重廣 卓也",
 "Takumi Nagaishi": "永石 拓海",
 "Daiki Miya": "宮 大樹",
 "Shion Homma": "本間 至恩",
 "Aleksandar Mitrović": "亚历山大·米特罗维奇",
 "Itsuki Oda": "小田 逸稀",
 "Takumu Kawamura": "川村 拓夢",
 "Kanji Okunuki": "奥抜 侃志",
 "Daiju Sasaki": "佐々木 大樹",
 "Sachiro Toshima": "戸嶋 祥郎",
 "Taiki Watanabe": "渡邊 泰基",
 "Hidemasa Morita": "守田 英正",
 "Temma Matsuda": "松田 天馬",
 "Hisashi Appiah Tawiah": "アピア タウィア 久",
 "İlkay Gündoğan": "伊尔卡伊·京多安",
 "Yuya Oki": "沖 悠哉",
 "Mohammed Kudus": "库杜斯",
 "Gonçalo Ramos": "贡萨洛·拉莫斯",
 "Yuichi Hirano": "平野 佑一",
 "Masaki Watai": "渡井 理己",
 "Shusuke Ota": "太田 修介",
 "Will Donkin": "William Rupert James Donkin ; 沈子貴",
 "Kosuke Yamazaki": "山﨑 浩介",
 "Shuhei Tokumoto": "徳元 悠平",
 "Shuta Doi": "土居 柊太",
 "Naoto Misawa": "三沢 直人",
 "Soya Fujiwara": "藤原 奏哉",
 "Keita Yamashita": "山下 敬大",
 "Daiki Kaneko": "金子 大毅",
 "Shinya Nakano": "中野 伸哉",
 "Masato Sasaki": "佐々木 雅士",
 "Kakeru Yamauchi": "山内 翔",
 "Ryotaro Araki": "荒木 遼太郎",
 "Shunsuke Mito": "三戸 舜介",
 "Xavi Simons": "哈维·西蒙斯",
 "Junya Suzuki": "鈴木 準弥",
 "Taiga Hata": "畑 大雅",
 "Hiroya Matsumoto": "松本 大弥",
 "Kashif Bangnagande": "バングーナガンデ　佳史扶",
 "Yuji Kitajima": "北島 祐二",
 "Florian Wirtz": "维尔茨",
 "Tsuyoshi Watanabe": "渡辺 剛",
 "Hayato Araki": "荒木 隼人",
 "Daisuke Yokota": "横田 大祐",
 "Yuto Yamada": "山田 雄士",
 "Riku Nakayama": "中山 陸",
 "Kaito Yasui": "安居 海渡",
 "Aidan Liu": "Aidan Bardina Liu 刘威登",
 "Taishi Brandon Nozawa": "野澤 大志 ブランドン",
 "Tatsuhiro Sakamoto": "坂元 達裕",
 "Yasuyuki Konno": "今野 泰幸",
 "Kisho Yano": "矢野 貴章",
 "Jiahao Wang": "王佳豪",
 "Julián Alvarez": "胡利安·阿尔瓦雷斯",
 "Daiki Matsuoka": "松岡 大起",
 "Shinnosuke Fukuda": "福田 心之助",
 "Reo Yasunaga": "安永 玲央",
 "Kai Shibato": "柴戸 海",
 "Shunki Higashi": "東 俊希",
 "Jamal Musiala": "穆夏拉",
 "Jude Bellingham": "朱德·贝林厄姆",
 "Thomas Müller": "托马斯·穆勒",
 "Riku Ochiai": "落合 陸",
 "Ayase Ueda": "上田 綺世",
 "Tojiro Kubo": "久保 藤次郎",
 "Kiyoshiro Tsuboi": "坪井 清志郎",
 "Kennedy Egbus Mikuni": "三國 ケネディ エブス",
 "Yuki Ohashi": "大橋 祐紀",
 "Yushi Hasegawa": "長谷川 雄志",
 "Hiroki Akiyama": "秋山 裕紀",
 "Itsuki Enomoto": "榎本 樹",
 "Katsunori Ueebisu": "上夷 克典",
 "Hikaru Nakahara": "中原 輝",
 "Yuta Higuchi": "樋口 雄太",
 "Yuya Asano": "浅野 雄也",
 "Kazuki Fujita": "藤田 和輝",
 "Ryuho Kikuchi": "菊池 流帆",
 "Yoshio Koizumi": "小泉 佳穂",
 "Nanasei Iino": "飯野 七聖",
 "Wataru Harada": "原田 亘",
 "Shun Yoshida": "吉田 舜",
 "Kaishu Sano": "佐野 海舟",
 "Fuchi Honda": "本田 風智",
 "Yusuke Matsuo": "松尾 佑介",
 "Kaito Mizuta": "水多 海斗",
 "Shuto Abe": "安部 柊斗",
 "Kyota Tokiwa": "常盤 亨太",
 "Yuta Matsumura": "松村 優太",
 "Ryoya Morishita": "森下 龍矢",
 "Tsuyoshi Ogashiwa": "小柏 剛",
 "Hidehiro Sugai": "須貝 英大",
 "Tomoya Fujii": "藤井 智也",
 "Wataru Iwashita": "岩下 航",
 "Neymar": "内马尔",
 "Itsuki Someno": "染野 唯月",
 "Tatsuki Seko": "瀬古 樹",
 "Hotaka Nakamura": "中村 帆高",
 "Tomoki Hayakawa": "早川 友基",
 "Makoto Mitsuta": "満田 誠",
 "Haruto Usui": "薄井 覇斗",
 "Taichi Kikuchi": "菊地 泰智",
 "Kyo Sato": "佐藤 響",
 "Yuta Miyamoto": "宮本 優太",
 "Tomoaki Okubo": "大久保 智明",
 "Keita Nakano": "中野 桂太",
 "Ryuma Nakano": "中野 瑠馬",
 "Koki Hinokio": "檜尾 昂樹",
 "Daichi Hayashi": "林 大地",
 "Ayumu Ohata": "大畑 歩夢",
 "Shun Ayukawa": "鮎川 峻",
 "Christian Eriksen": "克里斯蒂安·埃里克森",
 "Joel Chima Fujita": "藤田 譲瑠チマ",
 "Leon Nozawa": "野澤 零温",
 "Takashi Uchino": "内野 貴史",
 "Gavi": "加维",
 "Shinichi Chan": "陳晉一",
 "Enzo Fernández": "恩佐·费尔南德斯",
 "Naoto Arai": "新井 直人",
 "Ikuma Sekigawa": "関川 郁万",
 "Takuro Kaneko": "金子 拓郎",
 "Yamato Wakatsuki": "若月 大和",
 "Teppei Oka": "岡 哲平",
 "Mao Hosoya": "細谷 真大",
 "Satoshi Tanaka": "田中 聡",
 "Fumiya Unoki": "鵜木 郁哉",
 "Taiki Kagayama": "加賀山 泰毅",
 "Hidetoshi Takeda": "武田 英寿",
 "Yuito Suzuki": "鈴木 唯人",
 "Kazuki Kumasawa": "熊澤 和希",
 "Yudai Fujiwara": "藤原 優大",
 "Yota Komi": "小見 洋太",
 "Naoki Hayashi": "林 尚輝",
 "Michael James Fitzgerald": "舞行龍 ジェームズ",
 "Kazunari Ono": "大野 和成",
 "Nobuhiro Kato": "加藤 順大",
 "Hiroyuki Takasaki": "高崎 寛之",
 "Genki Haraguchi": "原口 元気",
 "Naoki Yamada": "山田 直輝",
 "Kota Mizunuma": "水沼 宏太",
 "Shu Kurata": "倉田 秋",
 "Yuto Nagatomo": "長友 佑都",
 "Shun Nagasawa": "長沢 駿",
 "Yohei Takeda": "武田 洋平",
 "Daiki Niwa": "丹羽 大輝",
 "Takumi Miyayoshi": "宮吉 拓実",
 "Daigo Nishi": "西 大伍",
 "Kodai Nagata": "永田 倖大",
 "Takuji Yonemoto": "米本 拓司",
 "Kenta Matsumoto": "松本 健太",
 "So Kawahara": "河原 創",
 "Takahiro Akimoto": "明本 考浩",
 "Sota Kawasaki": "川﨑 颯太",
 "Seiya Maikuma": "毎熊 晟矢",
 "Tetsuya Chinen": "知念 哲矢",
 "Kai Matsuzaki": "松崎 快",
 "Alpha Sawaneh Kubota": "窪田アルファサワネ",
 "Ryonosuke Kabayama": "樺山 諒乃介",
 "Leon Suzuki": "鈴木 太陽 レオン , Leon Taiyo Suzuki",
 "Daisuke Matsumoto": "松本 大輔",
 "Mario Götze": "马里奥·格策",
 "Takuto Kato": "加藤 匠人",
 "Tatsunori Sakurai": "櫻井 辰徳",
 "Isa Sakamoto": "坂本 一彩",
 "Takumi Narasaka": "奈良坂 巧",
 "Masato Morishige": "森重 真人",
 "Shusaku Nishikawa": "西川 周作",
 "Shinji Kagawa": "香川 真司",
 "Maya Yoshida": "吉田 麻也",
 "Cristiano Ronaldo": "克里斯蒂亚诺·罗纳尔多",
 "Yu Funabashi": "舩橋 佑",
 "Olivier Giroud": "奥利维耶·吉鲁",
 "Hayato Tanaka": "田中 隼人",
 "Hiroki Sakai": "酒井 宏樹",
 "Toru Hasegawa": "長谷川 徹",
 "Takumi Tsuchiya": "土屋 巧",
 "Yu Hirakawa": "平河 悠",
 "Lamine Yamal": "拉明·亚马尔",
 "Yugo Masukake": "升掛 友護",
 "Ryunosuke Sato": "佐藤 龍之介",
 "Taiyo Yamaguchi": "山口 太陽",
 "Wataru Goto": "後藤 亘",
 "Zento Uno": "宇野 禅斗",
 "Yosuke Furukawa": "古川 陽介",
 "Hayate Matsuda": "松田 隼風",
 "Kodai Sano": "佐野 航大",
 "Jumpei Hayakawa": "早川 隼平",
 "Shuhei Mizoguchi": "溝口 修平",
 "Rikuto Iida": "飯田 陸斗",
 "Kazunari Kita": "喜多 壱也",
 "Niina Tominaga": "冨永 虹七",
 "Sora Hiraga": "平賀 大空",
 "Kenshin Yasuda": "保田 堅心",
 "Sora Tanaka": "田中 想来",
 "Keisuke Goto": "後藤 啓介",
 "Ken Higuchi": "樋口 堅",
 "Rei Okada": "岡田 玲",
 "Naoki Kumata": "熊田 直紀",
 "Kota Tawaratsumida": "俵積田 晃太",
 "Kanta Doi": "土肥 幹太",
 "Masataka Kobayashi": "小林 将天",
 "Kalidou Koulibaly": "卡利杜·库利巴利",
 "James Rodríguez": "詹姆斯·罗德里格斯",
 "Kevin De Bruyne": "凯文·德布劳内",
 "Ryan Leijten": "Ryan Yang Leijten, 杨瑞安",
 "Yudai Kimura": "木村 勇大",
 "Kodai Mori": "森 昂大",
 "Kuryu Matsuki": "松木 玖生",
 "Rio Nitta": "二田 理央",
 "Ayumu Yokoyama": "横山 歩夢",
 "Yuya Kuwasaki": "鍬先 祐弥",
 "Arda Güler": "居莱尔",
 "Akihiro Ienaga": "家長 昭博",
 "Mu Kanazaki": "金崎 夢生",
 "Hiroshi Kiyotake": "清武 弘嗣",
 "Toki Hirosawa": "廣澤 灯喜",
 "Keisuke Shimizu": "清水 圭介",
 "Masakazu Tashiro": "田代 真一",
 "Taichi Fukui": "福井 太智",
 "Kota Kudo": "工藤 孝太",
 "Takashi Inui": "乾 貴士",
 "Yuta Arai": "荒井 悠汰",
 "Hugo Kametani": "亀谷 宇々護",
 "Ronaldo Nazário": "罗纳尔多·纳扎里奥",
 "Zinedine Zidane": "齐内丁·齐达内",
 "Miroslav Klose": "米罗斯拉夫·克洛泽",
 "David Villa": "大卫·比利亚",
 "Andrés Iniesta": "安德烈斯·伊涅斯塔",
 "Xavi Hernández": "哈维·埃尔南德斯",
 "Ronaldinho": "罗纳尔迪尼奥",
 "Thierry Henry": "蒂埃里·亨利",
 "Son Heung-min": "孙兴慜",
 "Mitoma Kaoru": "三笘薰",
 "Diego Forlán": "迭戈·弗兰",
 "Wesley Sneijder": "韦斯利·斯内德",
 "Arjen Robben": "阿尔扬·罗本",
 "Robin van Persie": "罗宾·范佩西",
 "Ivan Rakitić": "伊万·拉基蒂奇",
 "Eden Hazard": "埃登·阿扎尔",
 "Samuel Eto'o": "萨穆埃尔·埃托奥",
 "Gareth Bale": "加雷斯·贝尔",
 "Mario Mandžukić": "马里奥·曼朱基奇",
 "Diego Maradona": "迭戈·马拉多纳",
 "Pelé": "贝利",
 "Lothar Matthäus": "洛塔尔·马特乌斯",
 "Franz Beckenbauer": "弗兰茨·贝肯鲍尔",
 "Johan Cruyff": "约翰·克鲁伊夫",
 "Michel Platini": "米歇尔·普拉蒂尼",
 "Roberto Baggio": "罗伯托·巴乔",
 "Gabriel Batistuta": "加布里埃尔·巴蒂斯图塔",
 "Dennis Bergkamp": "丹尼斯·博格坎普",
 "Luís Figo": "路易斯·菲戈",
 "Toni Kroos": "托尼·克罗斯",
 "Rio Ferdinand": "里奥·费迪南德",
 "Steven Gerrard": "史蒂文·杰拉德",
 "Andrea Pirlo": "安德烈亚·皮尔洛",
 "Gianluigi Buffon": "吉安路易吉·布冯",
 "Didier Drogba": "迪迪埃·德罗巴",
 "Salem Al-Dawsari": "萨勒姆·达瓦萨里",
 "Salman Al-Faraj": "萨勒曼·法拉杰",
 "Takehiro Tomiyasu": "冨安 健洋"
};

(function(){ if(typeof playerDB!=='undefined'){var a=0;for(var k in window.__playerCNMap){if(playerDB[k]&&!playerDB[k].cn){playerDB[k].cn=window.__playerCNMap[k];a++;}} if(a)console.log('✅ 中文名已应用: '+a+' 人');} })();
