// ===== 球员中文名映射 (本地构建 — 2026-06-23T03:05:56.378Z) =====
// 来源: playerDB nn/n CJK字段 + engine.js _knownPlayerNames + givenName/surnameMap
// 覆盖: 1450/26357 (5.50%)
// 待 Wikidata 批量查询后补充剩余 24907 人
window.__playerCNMap = {
 "John Stones": "约翰·斯通斯",
 "Ben Davies": "戴维斯·本",
 "Emiliano Martínez": "埃米利亚诺·马丁内斯",
 "Néstor Araujo": "内斯托尔·阿劳若",
 "Kyle Walker": "凯尔·沃克",
 "Lautaro Martínez": "劳塔罗·马丁内斯",
 "Théo Hernandez": "特奥·埃尔南德斯",
 "Paulo Dybala": "保罗·迪巴拉",
 "Mitsuki Hidaka": "日髙 光揮",
 "Iker Moreno": "莫雷诺·伊克尔",
 "Alexander Romero": "罗梅罗·亚历山大",
 "Jesús López": "洛佩斯·赫苏斯",
 "Min-hyeok Yang": "양민혁",
 "Gabriel Silva": "席尔瓦·加布里埃尔",
 "Rubén Ramos": "拉莫斯·鲁本",
 "Sebastián Rodríguez": "罗德里格斯·塞巴斯蒂安",
 "Taisei Kuwata": "桒田 大誠",
 "Martín Rodríguez": "罗德里格斯·马丁",
 "Robin González": "冈萨雷斯·罗宾",
 "Rinto Hanashiro": "花城 琳斗",
 "Christian Müller": "穆勒·克里斯蒂安",
 "Shuto Nagano": "永野 修都",
 "Gabriel López": "洛佩斯·加布里埃尔",
 "Gonzalo Díaz": "迪亚斯·冈萨洛",
 "Tim Schulz": "舒尔茨·蒂姆",
 "Gotoku Sakai": "酒井 高徳",
 "Takahiro Nakazato": "中里 崇宏",
 "Simon Thomas": "托马斯·西蒙",
 "Tomás Silva": "席尔瓦·托马斯",
 "James Wilson": "威尔逊·哈梅斯",
 "Cody Johnson": "约翰逊·科迪",
 "Denilson Santos": "德尼尔森",
 "Eduardo Fernandez": "费尔南德斯·爱德华多",
 "Shogo Nishikawa": "西河 翔吾",
 "Gabriel Fernandes": "费尔南德斯·加布里埃尔",
 "Andrés García": "加西亚·安德雷斯",
 "Kentaro Sato": "佐藤 健太郎",
 "Takumi Yamada": "山田 拓巳",
 "Sebastián González": "冈萨雷斯·塞巴斯蒂安",
 "Álex Jimenez": "希门尼斯·亚历克斯",
 "Toni Fernández": "费尔南德斯·托尼",
 "Min-su Kim": "김민수",
 "Alejandro Gomes Rodríguez": "罗德里格斯·亚历杭德罗",
 "Manabu Saito": "齋藤 学",
 "Hinata Gonda": "権田 陽大",
 "Jung-woo So": "소정우",
 "Takashi Usami": "宇佐美 貴史",
 "Shunya Suganuma": "菅沼 駿哉",
 "David Martínez": "马丁内斯·大卫",
 "Ángel Pérez": "佩雷斯·安赫尔",
 "Kaito Matsuzawa": "松澤 海斗",
 "Marcos Alonso": "阿隆索·马科斯",
 "Kazuyoshi Miura": "三浦 知良",
 "Kento Hamasaki": "濱 健斗",
 "Yumeki Yoshinaga": "吉永 夢希",
 "Soma Anzai": "安斎 颯馬",
 "Rubén Pérez": "佩雷斯·鲁本",
 "Seung-soo Park": "박승수",
 "Keigo Higashi": "東 慶悟",
 "Masaaki Higashiguchi": "東口 順昭",
 "Hiroki Sekine": "関根 大輝",
 "Shunsuke Ando": "安藤 駿介",
 "Masato Kudo": "工藤 壮人",
 "Kyohei Noborizato": "登里 享平",
 "Shohei Takahashi": "高橋 祥平",
 "Alexis Martinez": "马丁内斯·亚历克西斯",
 "Rento Takaoka": "高岡 伶颯",
 "Jesús Díaz": "迪亚斯·赫苏斯",
 "Bruno Martinez": "马丁内斯·布鲁诺",
 "Kosuke Taketomi": "武富 孝介",
 "Tomás Pérez": "佩雷斯·托马斯",
 "Daniel Silva": "席尔瓦·丹尼尔",
 "Diego Díaz": "迪亚斯·迭戈",
 "Jonathan Jesus": "热苏斯·乔纳森",
 "Nathan Fernandes": "费尔南德斯·内森",
 "Thibaut Courtois": "蒂博·库尔图瓦",
 "Yuya Osako": "大迫 勇也",
 "Joe Johnson": "约翰逊·乔",
 "Aurélien Petit": "佩蒂·奥雷利安",
 "Vinicius Kanu": "卡努·维尼修斯",
 "Bebeto": "贝贝托",
 "Mario Martínez": "马丁内斯·马里奥",
 "Sergio Araujo": "阿劳若·塞尔吉奥",
 "Takuya Wada": "和田 拓也",
 "Il-lok Yun": "윤일록",
 "Ryo Nagai": "永井 龍",
 "Kohei Kawata": "河田 晃兵",
 "Tsuyoshi Kodama": "児玉 剛",
 "Harry Kane": "哈里·凯恩",
 "Dong-jin Kim": "김동진",
 "Chang-geun Lee": "이창근",
 "Raheem Sterling": "拉希姆·斯特林",
 "Yo-han Go": "고요한",
 "George Williams": "威廉姆斯·乔治",
 "Suguru Hino": "日野 優",
 "Christian Ortíz": "奥尔蒂斯·克里斯蒂安",
 "João Carlos": "卡洛斯·若昂",
 "Kunimitsu Sekiguchi": "関口 訓充",
 "Dani Jiménez": "希门尼斯·达尼",
 "Francesco Rossi": "罗西·弗朗切斯科",
 "Jeong-ho Hong": "홍정호",
 "Da-sol Kim": "김다솔",
 "Young-gwon Kim": "김영권",
 "Jae-suk Oh": "오재석",
 "Jong-eun Lim": "임종은",
 "Nobuteru Nakagawa": "中川 敦瑛",
 "Diego Rodríguez": "罗德里格斯·迭戈",
 "Álvaro Morata": "阿尔瓦罗·莫拉塔",
 "Bo-kyung Kim": "김보경",
 "Min-woo Kim": "김민우",
 "Toshio Shimakawa": "島川 俊郎",
 "Sung-geun Choi": "최성근",
 "Hugo González": "冈萨雷斯·乌戈",
 "David Davis": "戴维斯·大卫",
 "David López": "洛佩斯·大卫",
 "Sam Walker": "沃克·萨姆",
 "Nikki Havenaar": "ハーフナー ニッキ",
 "Ryo Miyaichi": "宮市 亮",
 "Gaku Shibasaki": "柴崎 岳",
 "Yoshiaki Takagi": "高木 善朗",
 "Kenyu Sugimoto": "杉本 健勇",
 "Tatsuya Uchida": "内田 達也",
 "Yuki Horigome": "堀米 勇輝",
 "Luís Silva": "席尔瓦·路易斯",
 "Hyun-jun Suk": "석현준",
 "Sung-jun Yoon": "윤성준 尹 星俊",
 "Juan Carlos": "卡洛斯·胡安",
 "Daniel Torres": "托雷斯·丹尼尔",
 "Ben Wilson": "威尔逊·本",
 "Hosei Kijima": "木島 萌生",
 "Goro Kawanami": "川浪 吾郎",
 "Juan Jesus": "热苏斯·胡安",
 "Nico Yennaris": "李可",
 "Daley Blind": "戴利·布林德",
 "Harry Davis": "戴维斯·哈里",
 "João Silva": "席尔瓦·若昂",
 "Patrick Schmidt": "施密特·帕特里克",
 "Yutaro Tsukada": "塚田 悠太郎",
 "Fernando González": "冈萨雷斯·费尔南多",
 "Antoine Griezmann": "安托万·格里兹曼",
 "Koki Kumasaka": "熊坂 光希",
 "Tatsuya Morita": "守田 達弥",
 "David Garcia": "加西亚·大卫",
 "Hideomi Yamamoto": "山本 英臣",
 "Christian Pérez": "佩雷斯·克里斯蒂安",
 "Hisashi Jogo": "城後 寿",
 "Min-young Lee": "이민영",
 "Manuel López": "洛佩斯·曼努埃尔",
 "Rodri Ríos": "罗德里",
 "Mizuki Hamada": "濱田 水輝",
 "Jin-hyeon Kim": "김진현",
 "Kenta Tanno": "丹野 研太",
 "Hotaru Yamaguchi": "山口 蛍",
 "Jesús Rodríguez": "罗德里格斯·赫苏斯",
 "Gonzalo Rodríguez": "罗德里格斯·冈萨洛",
 "Yu Kobayashi": "小林 悠",
 "Sergio Álvarez": "阿尔瓦雷斯·塞尔吉奥",
 "Virgil van Dijk": "维吉尔·范迪克",
 "Dani Rodríguez": "罗德里格斯·达尼",
 "Enner Valencia": "恩纳·瓦伦西亚",
 "Kook-young Han": "한국영",
 "Manuel García": "加西亚·曼努埃尔",
 "Leandro Díaz": "迪亚斯·莱安德罗",
 "Takahiro Ogihara": "扇原 貴宏",
 "Luis Rodríguez": "罗德里格斯·路易斯",
 "Yoshifumi Kashiwa": "柏 好文",
 "Diego Torres": "托雷斯·迭戈",
 "Kohei Kiyama": "喜山 康平",
 "Yuki Kobayashi": "小林 友希",
 "Max Meyer": "迈尔·马克斯",
 "Wataru Endo": "遠藤 航",
 "Manuel Bleda": "洛迪古斯",
 "Hugo Rodríguez": "罗德里格斯·乌戈",
 "Mohamed Salah": "穆罕默德·萨拉赫",
 "Ryan Hirooka": "広岡 ライアン勇輝",
 "Chul Hong": "홍철",
 "Martin Wagner": "瓦格纳·马丁",
 "Sang-gi Min": "민상기",
 "Shin-wook Kim": "김신욱",
 "Ryota Nagaki": "永木 亮太",
 "Su-hyeok Jo": "조수혁",
 "Tae-hwan Kim": "김태환",
 "Han-been Yang": "양한빈",
 "Tyias Browning": "蒋光太",
 "Daniel Schmidt": "シュミット ダニエル",
 "Serge Gnabry": "塞尔吉·格纳布里",
 "Manuel Torres": "托雷斯·曼努埃尔",
 "Joshua Kimmich": "约书亚·基米希",
 "Julian Günther-Schmidt": "施密特·胡利安",
 "Tomohiko Murayama": "村山 智彦",
 "Mario Müller": "穆勒·马里奥",
 "Kevin García": "加西亚·凯文",
 "Bit-garam Yoon": "윤빛가람",
 "Yuki Muto": "武藤 雄樹",
 "Shoma Doi": "土居 聖真",
 "Dong-won Ji": "지동원",
 "Ryota Oshima": "大島 僚太",
 "Gen Shoji": "昌子 源",
 "Adrien Rabiot": "阿德里安·拉比奥",
 "Davy Klaassen": "戴维·克拉森",
 "Karim Rossi": "罗西·卡里姆",
 "Kento Hashimoto": "橋本 拳人",
 "Jong-min Kim": "김종민",
 "Álvaro González": "冈萨雷斯·阿尔瓦罗",
 "Gabriel Araújo": "阿劳若·加布里埃尔",
 "Ming-Yang Yang": "杨明洋",
 "Nicolás López": "洛佩斯·尼古拉斯",
 "Yuya Kubo": "久保 裕也",
 "Yuzo Iwakami": "岩上 祐三",
 "Álex Martínez": "马丁内斯·亚历克斯",
 "Thomas Touré": "图雷·托马斯",
 "Tatsuki Nara": "奈良 竜樹",
 "Shoya Nakajima": "中島 翔哉",
 "Sei Muroya": "室屋 成",
 "Ayumi Niekawa": "牲川 歩見",
 "Naomichi Ueda": "植田 直通",
 "Yuto Shirai": "白井 裕人",
 "Sang-hun Yu": "유상훈",
 "Karim Benzema": "卡里姆·本泽马",
 "Juan Gabriel Rodríguez": "罗德里格斯·胡安",
 "Jonathan Silva": "席尔瓦·乔纳森",
 "Akira Fitzgerald": "フィッツジェラルド アキラ",
 "Unai López": "洛佩斯·乌奈",
 "Ryan Williams": "威廉姆斯·瑞安",
 "Leandro Silva": "席尔瓦·莱安德罗",
 "Leroy Sané": "勒鲁瓦·萨内",
 "Álex Moreno": "莫雷诺·亚历克斯",
 "Sung-dong Paik": "백성동",
 "Dong-geon No": "노동건",
 "Jan Koch": "科赫·扬",
 "Víctor García": "加西亚·维克托",
 "Shinya Yajima": "矢島 慎也",
 "Andreas Christensen": "安德烈亚斯·克里斯滕森",
 "Unai García": "加西亚·乌奈",
 "Tatsuya Tanaka": "田中 達也",
 "Takayuki Mae": "前 貴之",
 "João Schmidt": "施密特·若昂",
 "José Rodríguez": "罗德里格斯·若泽",
 "Fumiya Hayakawa": "早川 史哉",
 "Yuto Horigome": "堀米 悠斗",
 "Takuya Iwanami": "岩波 拓也",
 "Kyohei Yoshino": "吉野 恭平",
 "Takumi Minamino": "南野 拓実",
 "Memphis Depay": "孟菲斯·德佩",
 "Alessandro Martinelli": "马丁内利·亚历山德罗",
 "Daniel Johnson": "约翰逊·丹尼尔",
 "Kasper Schmeichel": "卡斯帕·舒梅切尔",
 "Noriyoshi Sakai": "酒井 宣福",
 "Adama Sarr": "萨尔·阿达马",
 "Bryan Pelé": "贝利",
 "Ryosuke Yamanaka": "山中 亮輔",
 "Riyad Mahrez": "里亚德·马赫雷斯",
 "Toni García": "加西亚·托尼",
 "Woo-young Jung": "정우영",
 "Yong-rae Lee": "이용래",
 "Jong-sung Lee": "이종성",
 "Manuel Neuer": "曼努埃尔·诺伊尔",
 "Sai van Wermeskerken": "ファン ウェルメスケルケン 際",
 "Sung-joon Kim": "김성준",
 "Dani Hernández": "埃尔南德斯·达尼",
 "Hayato Nakama": "仲間 隼斗",
 "Kazuki Saito": "齊藤 和樹",
 "Nathan Aké": "纳坦·阿克",
 "Tsukasa Shiotani": "塩谷 司",
 "Frank Romero": "ロメロ フランク",
 "Dani García": "加西亚·达尼",
 "Richard Sánchez": "桑切斯·理查德",
 "Hiroki Fujiharu": "藤春 廣輝",
 "Hugo Lloris": "雨果·洛里斯",
 "Luis García": "加西亚·路易斯",
 "Shota Kawanishi": "川西 翔太",
 "Sardar Azmoun": "萨达尔·阿兹蒙",
 "Kee-hee Kim": "김기희",
 "Piotr Zieliński": "彼得·泽林斯基",
 "George Evans": "埃文斯·乔治",
 "Ken Iwao": "岩尾 憲",
 "Shota Arai": "新井 章太",
 "Kevin Ray Mendoza": "门多萨·凯文",
 "João Cancelo": "若昂·坎塞洛",
 "Marcos Fernández": "费尔南德斯·马科斯",
 "Rivaldo González": "里瓦尔多",
 "Alex Lee": "李·亚历克斯",
 "Kosuke Kinoshita": "木下 康介",
 "Pablo González": "冈萨雷斯·巴勃罗",
 "Yuki Nogami": "野上 結貴",
 "José Aurelio Suárez": "苏亚雷斯·若泽",
 "Junki Kanayama": "金山 隼樹",
 "Il-gyu Park": "朴 一圭 パク イルギュ",
 "Dida": "迪达",
 "Seon-min Moon": "문선민",
 "Patrick Roberts": "罗伯茨·帕特里克",
 "Gabriel Davis": "戴维斯·加布里埃尔",
 "Yoshinori Muto": "武藤 嘉紀",
 "Hyeong-goo Ro": "노형구",
 "Dong-hyeon Do": "도동현",
 "Luis López": "洛佩斯·路易斯",
 "Andrew Robertson": "安德鲁·罗伯逊",
 "Akira Ibayashi": "井林 章",
 "Káká": "卡卡",
 "David Kong": "卡杜素",
 "Tim Müller": "穆勒·蒂姆",
 "Rivaldo": "里瓦尔多",
 "Sadio Mané": "萨迪奥·马内",
 "Ryan Thomas": "托马斯·瑞安",
 "Jack Grealish": "杰克·格里利什",
 "Cafú": "卡福",
 "Tomoya Inukai": "犬飼 智也",
 "Daiki Watari": "渡 大生",
 "Enzo Martinez": "马丁内斯·恩佐",
 "Haruya Ide": "井出 遥也",
 "Seok-ho Hwang": "황석호",
 "Romário": "罗马里奥",
 "Riki Harakawa": "原川 力",
 "Yuji Takahashi": "高橋 祐治",
 "Keita Hidaka": "日高 慶太",
 "Rubén García": "加西亚·鲁本",
 "Sho Sasaki": "佐 木 翔",
 "Ryohei Shirasaki": "白崎 凌兵",
 "Paulo Junichi Tanaka": "田中 パウロ 淳一",
 "Shun Takagi": "高木 駿",
 "Kohei Mihara": "三原 向平",
 "Vinícius Silva": "席尔瓦·维尼修斯",
 "Dennis Díaz": "迪亚斯·丹尼斯",
 "In-sung Kim": "김인성",
 "Óliver Torres": "托雷斯·奥利弗",
 "Keigo Numata": "沼田 圭悟",
 "Jung-hyun Kim": "김정현",
 "Young-kyu Ahn": "안영규",
 "Yong-jae Park": "박용재",
 "Hyun Kim": "김현",
 "Seung-kyu Lee": "이승규",
 "Chang-jin Moon": "문창진",
 "Dong-woon Shim": "심동운",
 "Jung-bin Park": "박정빈",
 "Gakuji Ota": "太田 岳志",
 "Mario González": "冈萨雷斯·马里奥",
 "Álvaro García": "加西亚·阿尔瓦罗",
 "Takeshi Kanamori": "金森 健志",
 "Yosuke Yuzawa": "湯澤 洋介",
 "Luka Jović": "卢卡·约维奇",
 "Rúben Dias": "鲁本·迪亚斯",
 "Pedro Delgado": "德尔加多",
 "Pêpê": "佩佩",
 "Vinícius Araújo": "阿劳若·维尼修斯",
 "Kazuhiro Sato": "佐藤 和弘",
 "Marcus Rashford": "马库斯·拉什福德",
 "Chang-hoon Kwon": "권창훈",
 "Jonathan Sánchez": "桑切斯·乔纳森",
 "Gabriel Fernández": "费尔南德斯·加布里埃尔",
 "Pyung-kang Chu": "추평강",
 "Hyeon-woo Jo": "조현우",
 "Ui-jo Hwang": "황의조",
 "Ji-su Park": "박지수",
 "Kyung-won Kwon": "권경원",
 "Kosuke Shirai": "白井 康介",
 "Yuzuru Shimada": "島田 譲",
 "Seung-joon Kim": "김승준",
 "Hyeon-cheol Jeong": "정현철",
 "Seung-woo Ryu": "류승우",
 "Ju-hun Song": "송주훈",
 "Ju-seong Woo": "우주성",
 "Sang-min Sim": "심상민",
 "Jei-min Yeon": "연제민",
 "Ángel Romero": "罗梅罗·安赫尔",
 "Hayao Kawabe": "川辺 駿",
 "Cheong-hyo Park": "박청효",
 "Ja-ryong Ku": "구자룡",
 "Min-kyu Joo": "주민규",
 "Juan Manuel Martínez": "马丁内斯·胡安",
 "Diego Martínez": "马丁内斯·迭戈",
 "Joe Williams": "威廉姆斯·乔",
 "Yusuke Chajima": "茶島 雄介",
 "Dong-jun Lee": "이동준",
 "Óliver Ortiz": "奥尔蒂斯·奥利弗",
 "Rúben Fernandes": "费尔南德斯·鲁本",
 "Sung-kuk Choi": "최성국",
 "Robin Becker": "贝克尔·罗宾",
 "Sung-yun Gu": "구성윤",
 "Ederson": "埃德森",
 "Álex García": "加西亚·亚历克斯",
 "Pablo Pérez": "佩雷斯·巴勃罗",
 "Leandro Rodríguez": "罗德里格斯·莱安德罗",
 "Bruno Fernandes": "布鲁诺·费尔南德斯",
 "Yoshihiro Nakano": "中野 嘉大",
 "Sang-hoon Ma": "마상훈",
 "Luis Caicedo": "凯塞多·路易斯",
 "Kingsley Coman": "金斯利·科曼",
 "Takuma Asano": "浅野 拓磨",
 "Naoki Maeda": "前田 直輝",
 "William Popp": "ポープ ウィリアム",
 "Daiki Kogure": "小暮 大器",
 "Yuhei Sato": "佐藤 優平",
 "Júlio César": "儒利奥·塞萨尔",
 "Brandon Thomas": "托马斯·布兰登",
 "Mario Rodríguez": "罗德里格斯·马里奥",
 "Tomoki Imai": "今井 智基",
 "Sergio Ramos": "塞尔希奥·拉莫斯",
 "Yuki Honda": "本多 勇喜",
 "Théo Zidane": "齐达内·特奥",
 "Giovanni González": "冈萨雷斯·乔瓦尼",
 "Álex Jiménez": "希门尼斯·亚历克斯",
 "Gianluca Ferrari": "法拉利·詹卢卡",
 "Juan Agüero": "阿圭罗·胡安",
 "Tyler Walker": "沃克·泰勒",
 "Axel Müller": "穆勒·阿克塞尔",
 "Tom Müller": "穆勒·汤姆",
 "Jeong-bin Lee": "이정빈",
 "Min-kyu Park": "박민규",
 "Kylian Mbappé": "基利安·姆巴佩",
 "José Enrique Ríos Alonso": "阿隆索·若泽",
 "Eon-hak Ji": "지언학",
 "Daniel Jiménez": "希门尼斯·丹尼尔",
 "Yoshinori Suzuki": "鈴木 義宜",
 "Christopher Nkunku": "恩昆库",
 "Dayot Upamecano": "达约·于帕梅卡诺",
 "Luis Martínez": "马丁内斯·路易斯",
 "Gabriel Díaz": "迪亚斯·加布里埃尔",
 "Teruhito Nakagawa": "仲川 輝人",
 "Yuma Suzuki": "鈴木 優磨",
 "Hisashi Ohashi": "大橋 尚志",
 "Yuta Nakayama": "中山 雄太",
 "Jonathan Cafu": "卡福",
 "Hiroki Noda": "野田 裕喜",
 "Daniel Álvarez": "阿尔瓦雷斯·丹尼尔",
 "Ángel González": "冈萨雷斯·安赫尔",
 "Shintaro Kurumaya": "車屋 紳太郎",
 "Joao Ortiz": "奥尔蒂斯·若昂",
 "Junya Ito": "伊東 純也",
 "Taiga Maekawa": "前川 大河",
 "Alexander Isak": "伊萨克",
 "Juan Familia-Castillo": "卡斯蒂略·胡安",
 "Juan Hernández": "埃尔南德斯·胡安",
 "Joshua Pérez": "佩雷斯·约书亚",
 "Yoichi Naganuma": "長沼 洋一",
 "Kazune Kubota": "久保田 和音",
 "Tsukasa Morishima": "森島 司",
 "Koki Ogawa": "小川 航基",
 "Marco Reus": "罗伊斯",
 "Juan de Alba": "阿尔巴·胡安",
 "Julián Navas": "纳瓦斯·胡利安",
 "Kylian Hazard": "阿扎尔·基利安",
 "Alexis Araújo": "阿劳若·亚历克西斯",
 "Alex Silva": "席尔瓦·亚历克斯",
 "Yuki Nakashima": "中島 裕希",
 "Álex González": "冈萨雷斯·亚历克斯",
 "Harry Wilson": "威尔逊·哈里",
 "Luka Modrić": "卢卡·莫德里奇",
 "Roberto Dias": "迪亚斯·罗伯托",
 "Lionel Messi": "利昂内尔·梅西",
 "Seung-woo Lee": "이승우",
 "Jonathan Rodríguez": "罗德里格斯·乔纳森",
 "Luis Milla": "米拉·路易斯",
 "Erik Palmer-Brown": "布朗·埃里克",
 "Álvaro Jiménez": "希门尼斯·阿尔瓦罗",
 "Giovanni Simeone": "西蒙尼·乔瓦尼",
 "Seung-ho Paik": "백승호",
 "Chang-yong Lee": "이창용",
 "Carles Pérez": "佩雷斯·卡尔斯",
 "Steven Bergwijn": "史蒂文·贝尔温",
 "Florian Müller": "穆勒·弗洛里安",
 "Ryosuke Kojima": "小島 亨介",
 "Yuta Koike": "小池 裕太",
 "Gonzalo Martinez": "马丁内斯·冈萨洛",
 "Ousmane Dembélé": "奥斯曼·登贝莱",
 "Federico Álvarez": "阿尔瓦雷斯·费德里科",
 "Rodri Martínez": "罗德里",
 "Kyoung-rok Choi": "최경록",
 "Sho Inagaki": "稲垣 祥",
 "Eduardo Pérez": "佩雷斯·爱德华多",
 "Jordi Sánchez": "桑切斯·若尔迪",
 "Hyung-mo Yang": "양형모",
 "Hirving Lozano": "伊尔文·洛萨诺",
 "Diego Rossi": "罗西·迭戈",
 "Wan-kyu Kwon": "권완규",
 "Yosuke Ideguchi": "井手口 陽介",
 "Ryun-do Kim": "김륜도",
 "Dae-young Goo": "구대영",
 "Dong-gyu Baek": "백동규",
 "Pil-soo Choe": "최필수",
 "Cy Goddard": "サイ ゴダード",
 "Denzel Dumfries": "登泽尔·邓弗里斯",
 "Sergio García": "加西亚·塞尔吉奥",
 "Matthijs de Ligt": "马泰斯·德利赫特",
 "Frenkie de Jong": "弗雷基·德容",
 "Robin Koch": "科赫·罗宾",
 "Diego Carlos": "卡洛斯·迭戈",
 "Jonathan González": "冈萨雷斯·乔纳森",
 "Romario Rösch": "罗马里奥",
 "Jonathan Klinsmann": "克林斯曼·乔纳森",
 "David Yeboah Johnson": "约翰逊·大卫",
 "Emilio Sánchez": "桑切斯·埃米利奥",
 "Toni Villa": "比利亚·托尼",
 "Hee-chan Hwang": "황희찬",
 "Seung-kyum Im": "임승겸",
 "Dong-su Kim": "김동수",
 "Sérgio Silva": "席尔瓦·塞尔吉奥",
 "Akito Fukuta": "福田 晃斗",
 "Dani Olmo": "达尼·奥尔莫",
 "Lucio Compagnucci": "卢西奥",
 "Kento Misao": "三竿 健斗",
 "Rikiya Motegi": "茂木 力也",
 "Koji Miyoshi": "三好 康児",
 "Ryoma Watanabe": "渡邊 凌磨",
 "Guillermo Ochoa": "吉列尔莫·奥乔亚",
 "Koya Yuruki": "汰木 康也",
 "Takahiro Sekine": "関根 貴大",
 "Tyler Roberts": "罗伯茨·泰勒",
 "Leandro Martínez": "马丁内斯·莱安德罗",
 "Woo-yeong Jeong": "정우영",
 "Young-wook Cho": "조영욱",
 "George Thomas": "托马斯·乔治",
 "José García": "加西亚·若泽",
 "Juan Pérez": "佩雷斯·胡安",
 "David García": "加西亚·大卫",
 "Toni Martínez": "马丁内斯·托尼",
 "Sergio Romero": "罗梅罗·塞尔吉奥",
 "Masaya Okugawa": "奥川 雅也",
 "Mehdi Taremi": "迈赫迪·塔雷米",
 "Ko Matsubara": "松原 后",
 "Shogo Taniguchi": "谷口 彰悟",
 "Kentaro Kakoi": "圍 謙太朗",
 "Ado Onaiwu": "オナイウ 阿道",
 "Jun Amano": "天野 純",
 "Tomoya Koyamatsu": "小屋松 知哉",
 "Kyle Dempsey": "邓普西·凯尔",
 "Hiroyuki Mae": "前 寛之",
 "Sergio González": "冈萨雷斯·塞尔吉奥",
 "Yohei Takaoka": "高丘 陽平",
 "Naoki Nomura": "野村 直輝",
 "Rikuto Hirose": "広瀬 陸斗",
 "Taiki Tamukai": "田向 泰輝",
 "Eiji Shirai": "白井 永地",
 "Eiichi Katayama": "片山 瑛一",
 "Kazuaki Mawatari": "馬渡 和彰",
 "Kazuhiko Chiba": "千葉 和彦",
 "Koki Anzai": "安西 幸輝",
 "Jun-ho Son": "손준호",
 "Kei Koizumi": "小泉 慶",
 "Álex López": "洛佩斯·亚历克斯",
 "Tom Davies": "戴维斯·汤姆",
 "Hyun-soo Hwang": "황현수",
 "Myung-jae Lee": "이명재",
 "Christian Pulisic": "克里斯蒂安·普利西奇",
 "Takaaki Shichi": "志知 孝明",
 "Romário Baró": "罗马里奥",
 "Leonardo Fernández": "费尔南德斯·莱昂纳多",
 "Jeferson Romário": "罗马里奥",
 "José Carrera-García": "加西亚·若泽",
 "Won-kyun Kim": "김원균",
 "Seung-hyun Jung": "정승현",
 "Tae-hee Lee": "이태희",
 "Hyun-woo Ju": "주현우",
 "Hyun-soo Jang": "장현수",
 "Tatsuya Ito": "伊藤 達哉",
 "Robert Lewandowski": "罗伯特·莱万多夫斯基",
 "Yasuki Kimoto": "木本 恭生",
 "Jin-ouk Kang": "강진욱",
 "Brandon Wilson": "威尔逊·布兰登",
 "Cayman Togashi": "富樫 敬真",
 "Tatsuya Hasegawa": "長谷川 竜也",
 "Daiki Hashioka": "橋岡 大樹",
 "Go Hatano": "波多野 豪",
 "Gyu-sung Lee": "이규성",
 "Unai Hernández": "埃尔南德斯·乌奈",
 "Shintaro Nago": "名古 新太郎",
 "Yuta Imazu": "今津 佑太",
 "Yuya Yamagishi": "山岸 祐也",
 "Sebastian Müller": "穆勒·塞巴斯蒂安",
 "Soon-hak Hong": "홍순학",
 "Takuma Nishimura": "西村 拓真",
 "Min-tae Kim": "김민태",
 "Ryoya Ogawa": "小川 諒也",
 "Mitsuki Saito": "齊藤 未月",
 "Keigo Tsunemoto": "常本 佳吾",
 "Hiroki Ito": "伊藤 洋輝",
 "Toshiki Takahashi": "高橋 利樹",
 "Yuto Iwasaki": "岩崎 悠人",
 "José Hernández": "埃尔南德斯·若泽",
 "Simón Moreno": "莫雷诺·西蒙",
 "Kengo Kitazume": "北爪 健吾",
 "Ko Itakura": "板倉 滉",
 "Seong-su Park": "박성수",
 "Ataru Esaka": "江坂 任",
 "Daichi Kamada": "鎌田 大地",
 "Hayato Nukui": "温井 駿斗",
 "Jurato Ikeda": "池田 樹雷人",
 "Masataka Nishimoto": "西本 雅崇",
 "Tomoki Iwata": "岩田 智輝",
 "Leon Schneider": "施奈德·莱昂",
 "Rafael Leão": "拉斐尔·莱昂",
 "Dušan Vlahović": "杜尚·弗拉霍维奇",
 "Rodri": "罗德里",
 "Declan Rice": "德克兰·赖斯",
 "Min-hyuk Kim": "김민혁",
 "Luis Pérez": "佩雷斯·路易斯",
 "Powell Obinna Obi": "オビ パウエル オビンナ",
 "Rubén Sánchez": "桑切斯·鲁本",
 "Ritsu Doan": "堂安 律",
 "Sebastián Sánchez": "桑切斯·塞巴斯蒂安",
 "Kohei Tezuka": "手塚 康平",
 "Masaaki Murakami": "村上 昌謙",
 "Yuji Hoshi": "星 雄次",
 "Gabriel Jesus": "加布里埃尔·热苏斯",
 "In-beom Hwang": "황인범",
 "Juan Torres": "托雷斯·胡安",
 "Federico Valverde": "费德里科·巴尔韦德",
 "Diego Hernández": "埃尔南德斯·迭戈",
 "Zico Bailey": "济科",
 "Vinicius Junior": "维尼修斯",
 "Dani Silva": "席尔瓦·达尼",
 "Yong-woo Park": "박용우",
 "Nicolas Fontaine": "方丹·尼古拉斯",
 "Akira Fantini": "ファンティーニ 燦",
 "Ryuji Izumi": "和泉 竜司",
 "Axel Rodríguez": "罗德里格斯·阿克塞尔",
 "Achraf Hakimi": "哈基米",
 "Ferran Torres": "费兰·托雷斯",
 "Andrew Jung": "郑·安德鲁",
 "Paul Jones": "琼斯·保罗",
 "Pablo López": "洛佩斯·巴勃罗",
 "Nicolás Fernández": "费尔南德斯·尼古拉斯",
 "Victor Osimhen": "维克托·奥斯梅恩",
 "Ju-an You": "유주안",
 "Dae-won Park": "박대원",
 "Jin-ya Kim": "김진야",
 "Sang-heon Lee": "이상헌",
 "Sang-hyeok Park": "박상혁",
 "O-yeon Cha": "차오연",
 "Se-hun Oh": "오세훈",
 "Ju-hyeon Lee": "이주현",
 "Jong-gyu Yoon": "윤종규",
 "Dani Fernández": "费尔南德斯·达尼",
 "Robert Sánchez": "桑切斯·罗伯特",
 "Alexis Sánchez": "桑切斯·亚历克西斯",
 "Tetsushi Yamakawa": "山川 哲史",
 "Ayumu Seko": "瀬古 歩夢",
 "Yukinari Sugawara": "菅原 由勢",
 "Shimpei Fukuoka": "福岡 慎平",
 "Taisei Miyashiro": "宮代 大聖",
 "Keito Nakamura": "中村 敬斗",
 "Issei Ouchi": "大内 一生",
 "Soichiro Kozuki": "上月 壮一郎",
 "Takefusa Kubo": "久保 建英",
 "Bruno Silva": "席尔瓦·布鲁诺",
 "Daniel Wagner": "瓦格纳·丹尼尔",
 "Phil Foden": "菲尔·福登",
 "Reiya Morishita": "森下 怜哉",
 "Diego García": "加西亚·迭戈",
 "Ismaïla Sarr": "伊斯梅拉·萨尔",
 "Atsushi Kawata": "河田 篤秀",
 "Thomas Henry": "亨利·托马斯",
 "In-soo Yu": "유인수",
 "Aurélien Tchouaméni": "奥雷利安·楚阿梅尼",
 "Ryo Hatsuse": "初瀬 亮",
 "Taiki Hirato": "平戸 太貴",
 "Yuki Kakita": "垣田 裕暉",
 "Koki Machida": "町田 浩樹",
 "Víctor Fernández": "费尔南德斯·维克托",
 "Satoki Uejo": "上門 知樹",
 "Ryotaro Ito": "伊藤 涼太郎",
 "Kanya Fujimoto": "藤本 寛也",
 "Keisuke Osako": "大迫 敬介",
 "Tomoya Wakahara": "若原 智哉",
 "José Martínez": "马丁内斯·若泽",
 "Keiya Shiihashi": "椎橋 慧也",
 "Masato Tokida": "常田 克人",
 "Kaito Anzai": "安西 海斗",
 "Kazunari Ichimi": "一美 和成",
 "Masato Yuzawa": "湯澤 聖人",
 "Erling Haaland": "埃尔林·哈兰德",
 "Masayuki Okuyama": "奥山 政幸",
 "Won-jin Jung": "정원진",
 "Masaya Tashiro": "田代 雅也",
 "Daizen Maeda": "前田 大然",
 "Jun Okano": "岡野 洵",
 "Kosuke Saito": "齋藤 功佑",
 "Shugo Tsuji": "辻 周吾",
 "Hiromu Mitsumaru": "三丸 拡",
 "Keita Endo": "遠藤 渓太",
 "Shun Nakamura": "中村 駿",
 "Daichi Tagami": "田上 大地",
 "Hugo Silva": "席尔瓦·乌戈",
 "Nicolás Silva": "席尔瓦·尼古拉斯",
 "Daigo Araki": "荒木 大吾",
 "Alphonso Davies": "阿方索·戴维斯",
 "Ivan Perišić": "伊万·佩里西奇",
 "Luis Suárez": "路易斯·苏亚雷斯",
 "Byeong-keun Hwang": "황병근",
 "Jun-jae Myung": "명준재",
 "Han-do Lee": "이한도",
 "Ben Brereton Díaz": "迪亚斯·本",
 "Jong-woo Kim": "김종우",
 "Gun-hee Kim": "김건희",
 "Jin-rae Kim": "김진래",
 "Seung-beom Ko": "고승범",
 "Ho-ik Jang": "장호익",
 "Je-woon Yeon": "연제운",
 "Jeong-hwan Kim": "김정환",
 "Min-hyeok Lim": "임민혁",
 "Chan-hee Han": "한찬희",
 "Ben Williams": "威廉姆斯·本",
 "Dong-jin Park": "박동진",
 "Jun-ho Hong": "홍준호",
 "In-jae Hwang": "황인재",
 "Dong-yun Jeong": "정동윤",
 "You-hyeon Lee": "이유현",
 "Geon-ung Kim": "김건웅",
 "Du-jae Won": "원두재",
 "José Luis Rodríguez": "罗德里格斯·若泽",
 "Ren Komatsu": "小松 蓮",
 "Marcos López": "洛佩斯·马科斯",
 "Zion Suzuki": "鈴木 彩艶",
 "Ryotaro Ishida": "石田 凌太郎",
 "Taichi Yamasaki": "山 大地",
 "Rihito Yamamoto": "山本 理仁",
 "Yutaro Oda": "小田 裕太郎",
 "Fuki Yamada": "山田 楓喜",
 "Sebastián Martínez": "马丁内斯·塞巴斯蒂安",
 "Bukayo Saka": "布卡约·萨卡",
 "Zico Asare": "济科",
 "Cody Gakpo": "科迪·加克波",
 "Yuya Nakasaka": "中坂 勇哉",
 "Tomás Romero": "罗梅罗·托马斯",
 "James Brown": "布朗·哈梅斯",
 "Ben Johnson": "约翰逊·本",
 "Jonathan Suárez": "苏亚雷斯·乔纳森",
 "Jacob Brown": "布朗·雅各布",
 "Kyosuke Tagawa": "田川 亨介",
 "Teruki Hara": "原 輝綺",
 "Denílson": "德尼尔森",
 "Marcos Álvarez": "阿尔瓦雷斯·马科斯",
 "Luis Díaz": "迪亚斯·路易斯",
 "Kevin Müller": "穆勒·凯文",
 "Wojciech Szczesny": "沃伊切赫·什琴斯尼",
 "Nathan Silva": "席尔瓦·内森",
 "Edouard Mendy": "爱德华·门迪",
 "Nathan Garcia": "加西亚·内森",
 "Shinji Yamada": "山田 真史",
 "Omar Marmoush": "马尔穆什",
 "Masaaki Takahara": "高原 正旭",
 "Yosuke Hanya": "半谷 陽介",
 "Max Schneider": "施奈德·马克斯",
 "Shinta Appelkamp": "アペルカンプ 真大 カール",
 "Shun Shibata": "柴田 駿",
 "Ángel Di María": "安赫尔·迪马利亚",
 "Álvaro Fernández": "费尔南德斯·阿尔瓦罗",
 "Carlos Duke": "デューク カルロス",
 "Juan Manuel García": "加西亚·胡安",
 "Takahiro Ko": "高 宇洋",
 "Ángel López": "洛佩斯·安赫尔",
 "Serge Müller": "穆勒·塞尔吉",
 "Jack Taylor": "泰勒·杰克",
 "Nicolás Olivera Rodríguez": "罗德里格斯·尼古拉斯",
 "Ayumu Kawai": "川井 歩",
 "Takahiro Iida": "飯田 貴敬",
 "Kota Yamada": "山田 康太",
 "Yugo Tatsuta": "立田 悠悟",
 "Kaito Abe": "阿部 海大",
 "Haruki Saruta": "猿田 遥己",
 "Lorenzo Colombo": "科隆博·洛伦佐",
 "Hiroki Abe": "安部 裕葵",
 "Leo Takae": "高江 麗央",
 "Taishi Matsumoto": "松本 泰志",
 "Daiya Maekawa": "前川 黛也",
 "Takuya Yasui": "安井 拓也",
 "Taiyo Koga": "古賀 太陽",
 "Ao Tanaka": "田中 碧",
 "Kaina Yoshio": "吉尾 海夏",
 "Wakaba Shimoguchi": "下口 稚葉",
 "Shohei Takeda": "武田 将平",
 "Takuya Shimamura": "島村 拓弥",
 "Keiya Sento": "仙頭 啓矢",
 "Chung-geun Jeong": "정충근",
 "Koki Tsukagawa": "塚川 孝輝",
 "Akinori Ichikawa": "市川 暉記",
 "Hiroki Mawatari": "馬渡 洋樹",
 "Ryo Toyama": "外山 凌",
 "Yuki Omoto": "大本 祐槻",
 "Kyogo Furuhashi": "古橋 亨梧",
 "Han-gil Kim": "김한길",
 "Roberto Fernández": "费尔南德斯·罗伯托",
 "Atsuki Ito": "伊藤 敦樹",
 "Takuya Ogiwara": "荻原 拓也",
 "Koki Yonekura": "米倉 恒貴",
 "Ryan Taylor": "泰勒·瑞安",
 "Taichi Hara": "原 大智",
 "Ka-ram Han": "한가람",
 "Reo Hatate": "旗手 怜央",
 "Sebastian Jung": "郑·塞巴斯蒂安",
 "Se-jin Park": "박세진",
 "Dong-su Lee": "이동수",
 "Dae-won Kim": "김대원",
 "Kyeong-jun Kim": "김경준",
 "Oliver Gerbig": "周緣德",
 "Yota Shimokawa": "下川 陽太",
 "Michael Davis": "戴维斯·迈克尔",
 "Shosei Okamoto": "岡本 將成",
 "Leo Kokubo": "小久保 玲央 ブライアン",
 "Shota Fujio": "藤尾 翔太",
 "Koki Saito": "斉藤 光毅",
 "Seiji Kimura": "木村 誠二",
 "Taiki Yamada": "山田 大樹",
 "Sang-min Lee": "이상민",
 "Yong-ho Yoon": "윤용호",
 "Joon-hyung Kim": "김준형",
 "Yuya Takazawa": "髙澤 優也",
 "Jelani Reshaun Sumiyoshi": "住吉 ジェラニレショーン",
 "Min-jae Kim": "김민재",
 "Tomás Araújo": "托马斯·阿劳若",
 "Eduardo García": "加西亚·爱德华多",
 "Giovanni Reyna": "乔瓦尼·雷纳",
 "Jack Evans": "埃文斯·杰克",
 "Tomoki Takamine": "高嶺 朋樹",
 "Kaoru Mitoma": "三笘 薫",
 "Kaito Taniguchi": "谷口 海斗",
 "Shogo Asada": "麻田 将吾",
 "Koki Fukui": "福井 光輝",
 "Fábio Silva": "席尔瓦·法比奥",
 "Takuya Shigehiro": "重廣 卓也",
 "Lucio Soldini": "卢西奥",
 "Sang-ki Lee": "이상기",
 "Ji-hoon Lee": "이지훈",
 "Brandon Williams": "威廉姆斯·布兰登",
 "Sang-ho Na": "나상호",
 "Takumi Nagaishi": "永石 拓海",
 "Daiki Miya": "宮 大樹",
 "Luis Müller": "穆勒·路易斯",
 "Seong-sun You": "유성순",
 "Shion Homma": "本間 至恩",
 "Dong-min Kim": "김동민",
 "Chang-rae Ha": "하창래",
 "Álex Suárez": "苏亚雷斯·亚历克斯",
 "Víctor López": "洛佩斯·维克托",
 "Aleksandar Mitrović": "亚历山大·米特罗维奇",
 "Diego González": "冈萨雷斯·迭戈",
 "Thomas Roberts": "罗伯茨·托马斯",
 "Julián Araujo": "阿劳若·胡利安",
 "Itsuki Oda": "小田 逸稀",
 "Takumu Kawamura": "川村 拓夢",
 "Kanji Okunuki": "奥抜 侃志",
 "Daiju Sasaki": "佐 木 大樹",
 "Sachiro Toshima": "戸嶋 祥郎",
 "Wesley Dias": "迪亚斯·韦斯利",
 "Bo-sub Kim": "김보섭",
 "Taiki Watanabe": "渡邊 泰基",
 "Sergio López": "洛佩斯·塞尔吉奥",
 "Hidemasa Morita": "守田 英正",
 "Moon-hwan Kim": "김문환",
 "Temma Matsuda": "松田 天馬",
 "Pablo Álvarez": "阿尔瓦雷斯·巴勃罗",
 "Jae-hyeon Mo": "모재현",
 "Cheol-won Choi": "최철원",
 "Tae-hyun An": "안태현",
 "Hyeong-jin Kim": "김형진",
 "Sang-yong Lee": "이상용",
 "Ji-hwan Mun": "문지환",
 "Ben Davis": "戴维斯·本",
 "Luis Hernández": "埃尔南德斯·路易斯",
 "Harry Williams": "威廉姆斯·哈里",
 "Hisashi Appiah Tawiah": "アピア タウィア 久",
 "Alexis Mac Allister": "亚历克西斯·麦卡利斯特",
 "Hugo Díaz": "迪亚斯·乌戈",
 "İlkay Gündoğan": "伊尔卡伊·京多安",
 "Pablo Rodríguez": "罗德里格斯·巴勃罗",
 "Yuya Oki": "沖 悠哉",
 "Bon-cheul Goo": "구본철",
 "Nicolás Caro Torres": "托雷斯·尼古拉斯",
 "Daniel Maldini": "马尔蒂尼·丹尼尔",
 "Enzo Díaz": "迪亚斯·恩佐",
 "Yun-oh Lee": "이윤오",
 "Moisés Rodríguez": "罗德里格斯·莫伊塞斯",
 "Jesús Álvarez": "阿尔瓦雷斯·赫苏斯",
 "Jonathan Fischer": "菲舍尔·乔纳森",
 "Luís Carlos": "卡洛斯·路易斯",
 "Ibrahim Kane": "凯恩·易卜拉欣",
 "Mohammed Kudus": "库杜斯",
 "Leandro González": "冈萨雷斯·莱安德罗",
 "Seong-hoon Cheon": "천성훈",
 "Nicolás Otamendi": "尼古拉斯·奥塔门迪",
 "Alejandro Pérez": "佩雷斯·亚历杭德罗",
 "Fabio Schneider": "施奈德·法比奥",
 "João Dias": "迪亚斯·若昂",
 "Leandro Dias": "迪亚斯·莱安德罗",
 "Gonçalo Ramos": "贡萨洛·拉莫斯",
 "Yuichi Hirano": "平野 佑一",
 "Masaki Watai": "渡井 理己",
 "Shusuke Ota": "太田 修介",
 "Hyeok-kyu Kwon": "권혁규",
 "Sang-jun Lee": "이상준",
 "Byung-hyun Park": "박병현",
 "Soo-il Park": "박수일",
 "Will Donkin": "沈子貴",
 "Kosuke Yamazaki": "山 浩介",
 "Shuhei Tokumoto": "徳元 悠平",
 "Shuta Doi": "土居 柊太",
 "Kang-in Lee": "이강인",
 "Jung-won Choi": "최정원",
 "Dong-gyeong Lee": "이동경",
 "In-pyo Oh": "오인표",
 "Jun-hyeok Choi": "최준혁",
 "Ho-yeong Park": "박호영",
 "Naoto Misawa": "三沢 直人",
 "Marcos Díaz": "迪亚斯·马科斯",
 "Bruno Bianchi": "比安基·布鲁诺",
 "Álvaro Rodríguez": "罗德里格斯·阿尔瓦罗",
 "Sung-wook Jo": "조성욱",
 "Enzo Pérez": "佩雷斯·恩佐",
 "Jin-woo Jeon": "전진우",
 "Byeong-chan Choe": "최병찬",
 "Soya Fujiwara": "藤原 奏哉",
 "Hyun-woo Kim": "김현우",
 "Kyle Taylor": "泰勒·凯尔",
 "Hyun-seok Hong": "홍현석",
 "Keita Yamashita": "山下 敬大",
 "Dong-hyeon Kim": "김동현",
 "Daiki Kaneko": "金子 大毅",
 "Shinya Nakano": "中野 伸哉",
 "Masato Sasaki": "佐 木 雅士",
 "Kakeru Yamauchi": "山内 翔",
 "Ryotaro Araki": "荒木 遼太郎",
 "Shunsuke Mito": "三戸 舜介",
 "Xavi Simons": "哈维·西蒙斯",
 "Junya Suzuki": "鈴木 準弥",
 "In-gyu Lee": "이인규",
 "Ju-sung Kim": "김주성",
 "Jong-beom Baek": "백종범",
 "Han-min Jung": "정한민",
 "Sung-yun Kwon": "권성윤",
 "Pablo Martínez": "马丁内斯·巴勃罗",
 "Roberto López": "洛佩斯·罗伯托",
 "Kyeong-min Kim": "김경민",
 "Taiga Hata": "畑 大雅",
 "Hiroya Matsumoto": "松本 大弥",
 "Kashif Bangnagande": "バングーナガンデ 佳史扶",
 "Yuji Kitajima": "北島 祐二",
 "Jae-hyun Go": "고재현",
 "Jin-wook Jeong": "정진욱",
 "Yun-ho Kwak": "곽윤호",
 "Florian Wirtz": "维尔茨",
 "Tsuyoshi Watanabe": "渡辺 剛",
 "Ángel Torres": "托雷斯·安赫尔",
 "Jonathan Júnior": "儒尼奥尔·乔纳森",
 "Andrés Sánchez": "桑切斯·安德雷斯",
 "Jonathan Martínez": "马丁内斯·乔纳森",
 "Jim-Patrick Müller": "穆勒·吉姆",
 "José González": "冈萨雷斯·若泽",
 "Hayato Araki": "荒木 隼人",
 "Daisuke Yokota": "横田 大祐",
 "Yuto Yamada": "山田 雄士",
 "Sergio Moreno": "莫雷诺·塞尔吉奥",
 "Éderson": "埃德森",
 "Alex Robertson": "罗伯逊·亚历克斯",
 "Tomas Basualdo Martínez": "马丁内斯·托马斯",
 "Jens Castrop": "옌스 카스트로프",
 "Riku Nakayama": "中山 陸",
 "Marcos Júnior": "儒尼奥尔·马科斯",
 "Kaito Yasui": "安居 海渡",
 "Wayne Brown": "布朗·韦恩",
 "Aidan Liu": "刘威登",
 "Diego López": "洛佩斯·迭戈",
 "Taishi Brandon Nozawa": "野澤 大志 ブランドン",
 "Juan Silva": "席尔瓦·胡安",
 "Tatsuhiro Sakamoto": "坂元 達裕",
 "Yasuyuki Konno": "今野 泰幸",
 "Alexander Díaz": "迪亚斯·亚历山大",
 "Kisho Yano": "矢野 貴章",
 "Jiahao Wang": "王佳豪",
 "Andrés Fernández": "费尔南德斯·安德雷斯",
 "Julián Alvarez": "胡利安·阿尔瓦雷斯",
 "Hyun-tae Kim": "김현태",
 "Min-ki Jeong": "정민기",
 "Daiki Matsuoka": "松岡 大起",
 "Shinnosuke Fukuda": "福田 心之助",
 "Reo Yasunaga": "安永 玲央",
 "Mario Fernández": "费尔南德斯·马里奥",
 "Kai Shibato": "柴戸 海",
 "Shunki Higashi": "東 俊希",
 "Tim Schmidt": "施密特·蒂姆",
 "Sergio Suárez": "苏亚雷斯·塞尔吉奥",
 "Jamal Musiala": "穆夏拉",
 "Samuel Iling-Junior": "儒尼奥尔·萨穆埃尔",
 "Jude Bellingham": "朱德·贝林厄姆",
 "Ji-min Park": "박지민",
 "David Alba": "阿尔巴·大卫",
 "Thomas Müller": "托马斯·穆勒",
 "Tae-joon Park": "박태준",
 "Riku Ochiai": "落合 陸",
 "Ayase Ueda": "上田 綺世",
 "Tojiro Kubo": "久保 藤次郎",
 "Anthony Jung": "郑·安东尼",
 "Kiyoshiro Tsuboi": "坪井 清志郎",
 "Kennedy Egbus Mikuni": "三國 ケネディ エブス",
 "Yuki Ohashi": "大橋 祐紀",
 "Manuel González": "冈萨雷斯·曼努埃尔",
 "James Henry": "亨利·哈梅斯",
 "Yushi Hasegawa": "長谷川 雄志",
 "David de Gea": "大卫·德赫亚",
 "Zico Buurmeester": "济科",
 "Jan Muller": "穆勒·扬",
 "Dani Sánchez": "桑切斯·达尼",
 "Unai Pérez": "佩雷斯·乌奈",
 "Ji-hun Cho": "조지훈",
 "David Rodríguez": "罗德里格斯·大卫",
 "June-hyuk Ahn": "안준혁",
 "Hiroki Akiyama": "秋山 裕紀",
 "Itsuki Enomoto": "榎本 樹",
 "Jun Choi": "최준",
 "Kwang-yeon Lee": "이광연",
 "Jae-sung Kim": "김재성",
 "Won-sang Um": "엄원상",
 "Rodri Sánchez": "罗德里",
 "Alejandro Fernández": "费尔南德斯·亚历杭德罗",
 "Katsunori Ueebisu": "上夷 克典",
 "Hikaru Nakahara": "中原 輝",
 "Rodri Val": "罗德里",
 "Yuta Higuchi": "樋口 雄太",
 "Yuya Asano": "浅野 雄也",
 "Pablo Valencia": "瓦伦西亚·巴勃罗",
 "Diego Moreno": "莫雷诺·迭戈",
 "Sergio Martínez": "马丁内斯·塞尔吉奥",
 "David González": "冈萨雷斯·大卫",
 "Jae-won Lee": "이재원",
 "Andrew Thomas": "托马斯·安德鲁",
 "Christian Martínez": "马丁内斯·克里斯蒂安",
 "Ryun-sung Kim": "김륜성",
 "Sang-bin Jeong": "정상빈",
 "Sang-hoon Paik": "백상훈",
 "Tae-seok Lee": "이태석",
 "Chan Kim": "김찬",
 "Jeong-hoon Kim": "김정훈",
 "Jin-seong Park": "박진성",
 "Kyu-hyun Park": "박규현",
 "Sang-jun Kim": "김상준",
 "Jae-hwan Hwang": "황재환",
 "Hyeon-gyu Oh": "오현규",
 "Ju-hwan Kim": "김주환",
 "Kazuki Fujita": "藤田 和輝",
 "Young-woo Seol": "설영우",
 "Ryuho Kikuchi": "菊池 流帆",
 "Jae-won Shin": "신재원",
 "Yoshio Koizumi": "小泉 佳穂",
 "Eduardo Camavinga": "爱德华多·卡马温加",
 "Nanasei Iino": "飯野 七聖",
 "Néstor Araújo": "内斯托尔·阿劳若",
 "Soo-bin Lee": "이수빈",
 "Wataru Harada": "原田 亘",
 "Shun Yoshida": "吉田 舜",
 "Leon Müller": "穆勒·莱昂",
 "Deok-geun Lim": "임덕근",
 "Jin-su Seo": "서진수",
 "Jesús González": "冈萨雷斯·赫苏斯",
 "Kaishu Sano": "佐野 海舟",
 "Mohamed-Ali Cho": "赵·穆罕默德",
 "Fuchi Honda": "本田 風智",
 "Robin Müller": "穆勒·罗宾",
 "Yusuke Matsuo": "松尾 佑介",
 "Ho-yeong Sung": "성호영",
 "Min-jun Kim": "김민준",
 "Sang-hee Kang": "강상희",
 "Paul Wagner": "瓦格纳·保罗",
 "Hyeong-kyeong Lee": "이형경",
 "Fabio Di Michele Sanchez": "桑切斯·法比奥",
 "Seung-min Jeon": "전승민",
 "Hyun-taek Cho": "조현택",
 "Kaito Mizuta": "水多 海斗",
 "Shuto Abe": "安部 柊斗",
 "Kyota Tokiwa": "常盤 亨太",
 "Yuta Matsumura": "松村 優太",
 "Ryoya Morishita": "森下 龍矢",
 "Tsuyoshi Ogashiwa": "小柏 剛",
 "Hidehiro Sugai": "須貝 英大",
 "Roberto Rodriguez": "罗德里格斯·罗伯托",
 "Tomoya Fujii": "藤井 智也",
 "Wataru Iwashita": "岩下 航",
 "Neymar": "内马尔",
 "Itsuki Someno": "染野 唯月",
 "Tatsuki Seko": "瀬古 樹",
 "Hotaka Nakamura": "中村 帆高",
 "Tomoki Hayakawa": "早川 友基",
 "Makoto Mitsuta": "満田 誠",
 "Haruto Usui": "薄井 覇斗",
 "Taichi Kikuchi": "菊地 泰智",
 "Kyo Sato": "佐藤 響",
 "Yuta Miyamoto": "宮本 優太",
 "Pedri": "佩德里",
 "Kevin Rodríguez": "罗德里格斯·凯文",
 "Tomoaki Okubo": "大久保 智明",
 "Keita Nakano": "中野 桂太",
 "Ryuma Nakano": "中野 瑠馬",
 "Rivaldo Lozano": "里瓦尔多",
 "Moisés Caicedo": "莫伊塞斯·凯塞多",
 "Koki Hinokio": "檜尾 昂樹",
 "Marcos Silva": "席尔瓦·马科斯",
 "Robert Wagner": "瓦格纳·罗伯特",
 "Daichi Hayashi": "林 大地",
 "Al Hassan Touré": "图雷·阿尔",
 "Ayumu Ohata": "大畑 歩夢",
 "Jonathan Pérez": "佩雷斯·乔纳森",
 "Shun Ayukawa": "鮎川 峻",
 "Christian Eriksen": "克里斯蒂安·埃里克森",
 "Ki-su Kim": "김기수",
 "Rodri Andrade": "罗德里",
 "Richard Taylor": "泰勒·理查德",
 "David Sánchez": "桑切斯·大卫",
 "Joel Chima Fujita": "藤田 譲瑠チマ",
 "Jordi Alba": "若尔迪·阿尔巴",
 "Leon Nozawa": "野澤 零温",
 "Takashi Uchino": "内野 貴史",
 "Iker Pérez": "佩雷斯·伊克尔",
 "Dani González": "冈萨雷斯·达尼",
 "Peter Thomas": "托马斯·彼得",
 "Han-beom Lee": "이한범",
 "Yong-hak Kim": "김용학",
 "Ji-sung Eom": "엄지성",
 "Hyun-ju Lee": "이현주",
 "Ji-han Lee": "이지한",
 "Seong-jin Kang": "강성진",
 "Ji-soo Kim": "김지수",
 "Sang-yun Kang": "강상윤",
 "Gabriel Torres": "托雷斯·加布里埃尔",
 "Ángel Jiménez": "希门尼斯·安赫尔",
 "Alex Rodríguez": "罗德里格斯·亚历克斯",
 "Denilson Gabionetta": "德尼尔森",
 "Kang-gook Kim": "김강국",
 "Sebastián Fernández": "费尔南德斯·塞巴斯蒂安",
 "Ja-ung Heo": "허자웅",
 "Tae-hyeon Kim": "김태현",
 "Gavi": "加维",
 "José Enrique": "恩里克·若泽",
 "Shinichi Chan": "陳晉一",
 "Enzo Fernández": "恩佐·费尔南德斯",
 "José López": "洛佩斯·若泽",
 "Naoto Arai": "新井 直人",
 "Sergio Busquets": "塞尔吉奥·布斯克茨",
 "Gue-sung Cho": "조규성",
 "Rubén Martínez": "马丁内斯·鲁本",
 "Jun-ho Hwang": "황준호",
 "Michael Koch": "科赫·迈克尔",
 "Seong-ung Maeng": "맹성웅",
 "Seong-soo Jeon": "전성수",
 "Tae-hoon Kim": "김태훈",
 "Gabriel Martinelli": "加布里埃尔·马丁内利",
 "Ju-yeop Kim": "김주엽",
 "Ikuma Sekigawa": "関川 郁万",
 "Takuro Kaneko": "金子 拓郎",
 "Yamato Wakatsuki": "若月 大和",
 "Seung-bin Kim": "김승빈",
 "Juan Camilo Castillo": "卡斯蒂略·胡安",
 "Yi-seok Kim": "김이석",
 "Teppei Oka": "岡 哲平",
 "Joe Rice": "赖斯·乔",
 "Mao Hosoya": "細谷 真大",
 "Satoshi Tanaka": "田中 聡",
 "Fumiya Unoki": "鵜木 郁哉",
 "Taiki Kagayama": "加賀山 泰毅",
 "David Müller": "穆勒·大卫",
 "Rodri Alonso": "罗德里",
 "Marcos Sánchez": "桑切斯·马科斯",
 "Juan Pablo Rodríguez": "罗德里格斯·胡安",
 "David Romero": "罗梅罗·大卫",
 "Hidetoshi Takeda": "武田 英寿",
 "Yuito Suzuki": "鈴木 唯人",
 "Kazuki Kumasawa": "熊澤 和希",
 "Alex Jiménez": "希门尼斯·亚历克斯",
 "Andrés Mendoza": "门多萨·安德雷斯",
 "Luis Sánchez": "桑切斯·路易斯",
 "Juan Riquelme": "里克尔梅·胡安",
 "Pável Pérez": "佩雷斯·帕维尔",
 "Yudai Fujiwara": "藤原 優大",
 "Yota Komi": "小見 洋太",
 "Naoki Hayashi": "林 尚輝",
 "Christian Torres": "托雷斯·克里斯蒂安",
 "Dong-hyeon You": "유동현",
 "Ki-hyun Um": "엄기현",
 "Michael James Fitzgerald": "舞行龍 ジェームズ",
 "Kazunari Ono": "大野 和成",
 "Nobuhiro Kato": "加藤 順大",
 "Hiroyuki Takasaki": "高崎 寛之",
 "Genki Haraguchi": "原口 元気",
 "Naoki Yamada": "山田 直輝",
 "Kota Mizunuma": "水沼 宏太",
 "Shu Kurata": "倉田 秋",
 "Keylor Navas": "凯洛尔·纳瓦斯",
 "Yuto Nagatomo": "長友 佑都",
 "Shun Nagasawa": "長沢 駿",
 "Yohei Takeda": "武田 洋平",
 "Daiki Niwa": "丹羽 大輝",
 "Takumi Miyayoshi": "宮吉 拓実",
 "Daigo Nishi": "西 大伍",
 "Thomas Fontaine": "方丹·托马斯",
 "Kodai Nagata": "永田 倖大",
 "Jun-ho Kim": "김준호",
 "Thomas Romero": "罗梅罗·托马斯",
 "Denilson": "德尼尔森",
 "Takuji Yonemoto": "米本 拓司",
 "Daniel Hernández": "埃尔南德斯·丹尼尔",
 "Seok-ju Hong": "홍석주",
 "Alejandro Garnacho": "亚历杭德罗·加纳乔",
 "Hugo Pérez": "佩雷斯·乌戈",
 "Gabriel Martínez": "马丁内斯·加布里埃尔",
 "Kevin Carlos": "卡洛斯·凯文",
 "Bruno Wilson": "威尔逊·布鲁诺",
 "Álvaro Martínez": "马丁内斯·阿尔瓦罗",
 "Patrick Jones": "琼斯·帕特里克",
 "Lautaro Díaz": "迪亚斯·劳塔罗",
 "Mikel Rodriguez": "罗德里格斯·米克尔",
 "Emiliano García": "加西亚·埃米利亚诺",
 "Federico Torres": "托雷斯·费德里科",
 "Philipp Müller": "穆勒·菲利普",
 "Marcos Pérez": "佩雷斯·马科斯",
 "Alejandro Martínez": "马丁内斯·亚历杭德罗",
 "Victor Petit": "佩蒂·维克托",
 "Kang-san Kim": "김강산",
 "Kenta Matsumoto": "松本 健太",
 "So Kawahara": "河原 創",
 "Takahiro Akimoto": "明本 考浩",
 "Sota Kawasaki": "川 颯太",
 "Seiya Maikuma": "毎熊 晟矢",
 "Tetsuya Chinen": "知念 哲矢",
 "Kai Matsuzaki": "松崎 快",
 "David Ospina": "大卫·奥斯皮纳",
 "In-gyun Kim": "김인균",
 "Alpha Sawaneh Kubota": "窪田アルファサワネ",
 "Alexandre Jesus": "热苏斯·亚历山大",
 "Eui-bin Kang": "강의빈",
 "Fábio Ronaldo": "罗纳尔多·法比奥",
 "Mohamed Touré": "图雷·穆罕默德",
 "Daniel da Silva": "席尔瓦·丹尼尔",
 "Christopher Garcia": "加西亚·克里斯托弗",
 "Ryonosuke Kabayama": "樺山 諒乃介",
 "Seung-min Um": "엄승민",
 "Leon Suzuki": "鈴木 太陽 レオン",
 "Daisuke Matsumoto": "松本 大輔",
 "Christian Schmidt": "施密特·克里斯蒂安",
 "Thomas Williams": "威廉姆斯·托马斯",
 "Mario Götze": "马里奥·格策",
 "Patrick Weah": "维阿·帕特里克",
 "Geon-joo Choi": "최건주",
 "Alex Williams": "威廉姆斯·亚历克斯",
 "Jae-yong Bak": "박재용",
 "Jason Ramos": "拉莫斯·杰森",
 "Alexander Meyer": "迈尔·亚历山大",
 "Ji-moog Choi": "최지묵",
 "Gi-hyuk Lee": "이기혁",
 "Luka Romero": "罗梅罗·卢卡",
 "Federico González": "冈萨雷斯·费德里科",
 "Pablo García": "加西亚·巴勃罗",
 "Gabriel Falcão": "法尔考·加布里埃尔",
 "Théo Gonzalez": "冈萨雷斯·特奥",
 "Takuto Kato": "加藤 匠人",
 "Tatsunori Sakurai": "櫻井 辰徳",
 "Isa Sakamoto": "坂本 一彩",
 "Takumi Narasaka": "奈良坂 巧",
 "Yun-gu Kang": "강윤구",
 "Masato Morishige": "森重 真人",
 "Shusaku Nishikawa": "西川 周作",
 "Shinji Kagawa": "香川 真司",
 "Maya Yoshida": "吉田 麻也",
 "Sung-ryong Jung": "정성룡",
 "Sung-yueng Ki": "기성용",
 "Chung-yong Lee": "이청용",
 "Cristiano Ronaldo": "克里斯蒂亚诺·罗纳尔多",
 "Fernando Martínez": "马丁内斯·费尔南多",
 "Yu Funabashi": "舩橋 佑",
 "David Suárez": "苏亚雷斯·大卫",
 "Martín Fernández": "费尔南德斯·马丁",
 "Olivier Giroud": "奥利维耶·吉鲁",
 "Hayato Tanaka": "田中 隼人",
 "Alexis Fernandez": "费尔南德斯·亚历克西斯",
 "Ángel García": "加西亚·安赫尔",
 "Hiroki Sakai": "酒井 宏樹",
 "Harry Lee": "李·哈里",
 "Toru Hasegawa": "長谷川 徹",
 "Benjamín Sánchez": "桑切斯·本杰明",
 "Christian Díaz": "迪亚斯·克里斯蒂安",
 "Ángel Ortiz": "奥尔蒂斯·安赫尔",
 "Gonzalo García": "加西亚·冈萨洛",
 "David Jiménez": "希门尼斯·大卫",
 "Takumi Tsuchiya": "土屋 巧",
 "Yu Hirakawa": "平河 悠",
 "Dani Díaz": "迪亚斯·达尼",
 "Lamine Yamal": "拉明·亚马尔",
 "Yugo Masukake": "升掛 友護",
 "Joe Taylor": "泰勒·乔",
 "Samuel Rodriguez": "罗德里格斯·萨穆埃尔",
 "Dani Martinez": "马丁内斯·达尼",
 "Ryunosuke Sato": "佐藤 龍之介",
 "Taiyo Yamaguchi": "山口 太陽",
 "Wataru Goto": "後藤 亘",
 "Anrie Chase": "チェイス アンリ",
 "Min-hyeok Kim": "김민혁",
 "Jesús Martínez": "马丁内斯·赫苏斯",
 "Zento Uno": "宇野 禅斗",
 "Yosuke Furukawa": "古川 陽介",
 "Hayate Matsuda": "松田 隼風",
 "Kodai Sano": "佐野 航大",
 "Manuel Sánchez": "桑切斯·曼努埃尔",
 "Sam Williams": "威廉姆斯·萨姆",
 "Ruben Müller": "穆勒·鲁本",
 "Hyung-min Shin": "신형민",
 "Lucio Berron": "卢西奥",
 "Joon-ho Lee": "이준호",
 "Jumpei Hayakawa": "早川 隼平",
 "Sang-hun Chu": "추상훈",
 "Fernando Álvarez": "阿尔瓦雷斯·费尔南多",
 "Jun-ho Bae": "배준호",
 "Shuhei Mizoguchi": "溝口 修平",
 "Tim Hoffmann": "霍夫曼·蒂姆",
 "Rikuto Iida": "飯田 陸斗",
 "Kazunari Kita": "喜多 壱也",
 "Niina Tominaga": "冨永 虹七",
 "Sora Hiraga": "平賀 大空",
 "Myung-jun Kim": "김명준",
 "Kenshin Yasuda": "保田 堅心",
 "Sora Tanaka": "田中 想来",
 "Keisuke Goto": "後藤 啓介",
 "Heung-min Son": "손흥민",
 "Jesús Fernández": "费尔南德斯·赫苏斯",
 "Yong Lee": "이용",
 "Ki-hun Yeom": "염기훈",
 "Jin-ho Lee": "이진호",
 "Ken Higuchi": "樋口 堅",
 "Rei Okada": "岡田 玲",
 "Naoki Kumata": "熊田 直紀",
 "Kota Tawaratsumida": "俵積田 晃太",
 "Kanta Doi": "土肥 幹太",
 "Masataka Kobayashi": "小林 将天",
 "Ibrahim Salah": "萨拉赫·易卜拉欣",
 "Kalidou Koulibaly": "卡利杜·库利巴利",
 "Dani Torres": "托雷斯·达尼",
 "Victor Ramos": "拉莫斯·维克托",
 "Gabriel Gonzalez": "冈萨雷斯·加布里埃尔",
 "Young-joon Lee": "이영준",
 "Luis Miguel Rodríguez": "罗德里格斯·路易斯",
 "Ji-ho Lee": "이지호",
 "Sun Yu": "유선",
 "James Rodríguez": "詹姆斯·罗德里格斯",
 "Joshua Johnson": "约翰逊·约书亚",
 "Kevin De Bruyne": "凯文·德布劳内",
 "Oliver Jones": "琼斯·奥利弗",
 "Leonardo Colombo": "科隆博·莱昂纳多",
 "Hugo Álvarez": "阿尔瓦雷斯·乌戈",
 "Ryan Leijten": "杨瑞安",
 "Lúcio": "卢西奥",
 "Yudai Kimura": "木村 勇大",
 "Kodai Mori": "森 昂大",
 "Álex Fernández": "费尔南德斯·亚历克斯",
 "José Müller": "穆勒·若泽",
 "Kuryu Matsuki": "松木 玖生",
 "Rio Nitta": "二田 理央",
 "Ayumu Yokoyama": "横山 歩夢",
 "Emilio Martínez": "马丁内斯·埃米利奥",
 "Seung-won Lee": "이승원",
 "Yuya Kuwasaki": "鍬先 祐弥",
 "José Manuel López": "洛佩斯·若泽",
 "Maicon": "麦孔",
 "Hee-seung Kim": "김희승",
 "Daniel Heuer Fernandes": "费尔南德斯·丹尼尔",
 "Chang-beom Hong": "홍창범",
 "Talla Ndao": "ンダウ ターラ",
 "Rodri Suárez": "罗德里",
 "Hyun-jun Yang": "양현준",
 "Sang-jun Cho": "조상준",
 "Tomás Rossi": "罗西·托马斯",
 "Chan-hui Hwang": "황찬희",
 "David Torres": "托雷斯·大卫",
 "Kang-min Choi": "최강민",
 "See-young Jang": "장시영",
 "Byung-kwan Jeon": "전병관",
 "Arda Güler": "居莱尔",
 "Akihiro Ienaga": "家長 昭博",
 "Mu Kanazaki": "金崎 夢生",
 "Hiroshi Kiyotake": "清武 弘嗣",
 "Toki Hirosawa": "廣澤 灯喜",
 "Keisuke Shimizu": "清水 圭介",
 "Masakazu Tashiro": "田代 真一",
 "Nicolás Romero": "罗梅罗·尼古拉斯",
 "Ji-seong Ryu": "류지성",
 "Sebastian Sanchez": "桑切斯·塞巴斯蒂安",
 "David Silva": "大卫·席尔瓦",
 "Tom Wilson-Brown": "布朗·汤姆",
 "Taichi Fukui": "福井 太智",
 "Kota Kudo": "工藤 孝太",
 "Hyun-wook Jung": "정현욱",
 "Romelu Lukaku": "罗梅卢·卢卡库",
 "Daniel Kanu": "卡努·丹尼尔",
 "Kevin González": "冈萨雷斯·凯文",
 "Jesús Moreno": "莫雷诺·赫苏斯",
 "Andrés Ferrari": "法拉利·安德雷斯",
 "Anthony Valencia": "瓦伦西亚·安东尼",
 "Jonathan Jiménez": "希门尼斯·乔纳森",
 "Sergio Rodríguez": "罗德里格斯·塞尔吉奥",
 "Emiliano Rodríguez": "罗德里格斯·埃米利亚诺",
 "Takashi Inui": "乾 貴士",
 "Alex Fernandes": "费尔南德斯·亚历克斯",
 "Yuta Arai": "荒井 悠汰",
 "Julián Fernández": "费尔南德斯·胡利安",
 "Diego Gonzalez": "冈萨雷斯·迭戈",
 "Hugo Kametani": "亀谷 宇 護",
 "Jacob Evans": "埃文斯·雅各布",
 "Benjamín Ortíz": "奥尔蒂斯·本杰明",
 "Leonardo Pérez": "佩雷斯·莱昂纳多",
 "Tomás González": "冈萨雷斯·托马斯",
 "Ousmane Touré": "图雷·奥斯曼",
 "Andrés Montaño": "蒙塔诺·安德雷斯",
 "Lorenzo Hernández": "埃尔南德斯·洛伦佐",
 "Ronaldo Nazário": "罗纳尔多·纳扎里奥",
 "Zinedine Zidane": "齐内丁·齐达内",
 "Miroslav Klose": "米罗斯拉夫·克洛泽",
 "David Villa": "大卫·比利亚",
 "Andrés Iniesta": "安德烈斯·伊涅斯塔",
 "Xavi Hernández": "哈维·埃尔南德斯",
 "Ronaldinho": "罗纳尔迪尼奥",
 "Thierry Henry": "蒂埃里·亨利",
 "Son Heung-min": "孙兴慜",
 "Mitoma Kaoru": "三笘薰",
 "Diego Forlán": "迭戈·弗兰",
 "Wesley Sneijder": "韦斯利·斯内德",
 "Arjen Robben": "阿尔扬·罗本",
 "Robin van Persie": "罗宾·范佩西",
 "Ivan Rakitić": "伊万·拉基蒂奇",
 "Eden Hazard": "埃登·阿扎尔",
 "Samuel Eto'o": "萨穆埃尔·埃托奥",
 "Gareth Bale": "加雷斯·贝尔",
 "Mario Mandžukić": "马里奥·曼朱基奇",
 "Diego Maradona": "迭戈·马拉多纳",
 "Pelé": "贝利",
 "Lothar Matthäus": "洛塔尔·马特乌斯",
 "Franz Beckenbauer": "弗兰茨·贝肯鲍尔",
 "Johan Cruyff": "约翰·克鲁伊夫",
 "Michel Platini": "米歇尔·普拉蒂尼",
 "Roberto Baggio": "罗伯托·巴乔",
 "Gabriel Batistuta": "加布里埃尔·巴蒂斯图塔",
 "Dennis Bergkamp": "丹尼斯·博格坎普",
 "Luís Figo": "路易斯·菲戈",
 "Toni Kroos": "托尼·克罗斯",
 "Rio Ferdinand": "里奥·费迪南德",
 "Steven Gerrard": "史蒂文·杰拉德",
 "Andrea Pirlo": "安德烈亚·皮尔洛",
 "Gianluigi Buffon": "吉安路易吉·布冯",
 "Didier Drogba": "迪迪埃·德罗巴",
 "Salem Al-Dawsari": "萨勒姆·达瓦萨里",
 "Salman Al-Faraj": "萨勒曼·法拉杰",
 "Jae-sung Lee": "이재성",
 "Alireza Jahanbakhsh": "阿里雷扎·贾汉巴赫什",
 "Takehiro Tomiyasu": "冨安 健洋",
 "Juan Camilo Hernandez": "埃尔南德斯·胡安",
 "Aya Suzuka": "铃木彩艶",
 "Kento Shiode": "塩手健人",
 "LEE Jaesung": "이재성"
};

// 自动应用到 playerDB
(function applyCNMap() {
    if (typeof playerDB === 'undefined') return;
    var applied = 0;
    for (var key in window.__playerCNMap) {
        if (playerDB[key] && !playerDB[key].cn) {
            playerDB[key].cn = window.__playerCNMap[key];
            applied++;
        }
    }
    if (applied > 0) console.log('✅ 中文名映射已应用: ' + applied + ' 人 (本地构建)');
})();
